export const PUBLICATIONS = [
  {
    title: 'Invisibility Coherence for Faster Scan-Line Hidden Surface Algorithms',
    authors: ['Gary A. Crocker'],
    publication: 'Computer Graphics: Proceedings of SIGGRAPH ’84',
    volume: '18',
    issue: '3',
    pages: '95–102',
    date: '1984-07',
    dateLabel: 'July 1984',
    doi: '10.1145/800031.808584',
    summary: 'Presents a visibility-coherence method for accelerating scan-line hidden-surface rendering by avoiding portions of a scene unlikely to contribute visible surfaces. The method applies to polygonal and parametrically curved surfaces.',
  },
  {
    title: 'Screen-Area Coherence for Interactive Scanline Display Algorithms',
    authors: ['Gary A. Crocker'],
    publication: 'IEEE Computer Graphics and Applications',
    volume: '7',
    issue: '9',
    pages: '10–17',
    date: '1987-09',
    dateLabel: 'September 1987',
    doi: '10.1109/MCG.1987.277050',
    summary: 'Recalculates only screen regions affected by geometric changes to make scan-line display more interactive for constructive-solid-geometry models. Reported tests reduced average frame-update time to roughly one quarter of a full redisplay.',
  },
  {
    title: 'Boundary Evaluation of Non-Convex Primitives to Produce Parametric Trimmed Surfaces',
    authors: ['Gary A. Crocker', 'William F. Reinke'],
    publication: 'Computer Graphics: Proceedings of SIGGRAPH ’87',
    volume: '21',
    issue: '4',
    pages: '129–136',
    date: '1987-07',
    dateLabel: 'July 1987',
    doi: '10.1145/37401.37418',
    summary: 'Describes boundary evaluation for non-convex primitives that produces parametric trimmed surfaces, supporting interaction between constructive-solid models and surface- or wireframe-oriented CAD representations.',
  },
  {
    title: 'An Editable Nonmanifold Boundary Representation',
    authors: ['Gary A. Crocker', 'William F. Reinke'],
    publication: 'IEEE Computer Graphics and Applications',
    volume: '11',
    issue: '2',
    pages: '39–51',
    date: '1991',
    dateLabel: '1991',
    doi: '10.1109/38.75589',
    summary: 'Develops an editable nonmanifold boundary-representation scheme supporting Boolean operations, surface and wireframe information, and retained input-primitive descriptions for subsequent editing.',
  },
];

export const TECHNICAL_DOCUMENTS = [
  {
    title: 'Boundary Evaluation of Solid Models: Algorithm Study and Implementation',
    authors: ['Gary A. Crocker'],
    type: 'Master’s thesis',
    publisher: 'Rensselaer Polytechnic Institute',
    date: '1988',
    summary: 'A more extensive treatment of boundary-evaluation algorithms underlying Crocker’s solid-modeling research, cited in later technical literature.',
  },
  {
    title: 'Boundary Evaluation in a Non-Manifold Environment',
    authors: ['Gary A. Crocker', 'William F. Reinke'],
    type: 'Technical report or prepublication material',
    date: '1989-11',
    dateLabel: 'November 1989',
    summary: 'A cataloged technical document of approximately 30 pages plus 16 pages of illustrations and a bibliography. Its subject overlaps the later work on editable nonmanifold boundary representations, although the catalog record does not establish that the documents are identical.',
  },
];
