// Centralized site data for nPower Software / Power Surfacing

export const IMAGES = {
  hero: "https://media.base44.com/images/public/6a44d2347ed5692671cd034a/405ae3473_generated_7bdd1c95.png",
  reStudio: "https://media.base44.com/images/public/6a44d2347ed5692671cd034a/51d89438c_generated_956497bb.png",
  studio: "https://media.base44.com/images/public/6a44d2347ed5692671cd034a/10d913a4c_generated_d7298fb6.png",
  solidworks: "https://media.base44.com/images/public/6a44d2347ed5692671cd034a/ea8b9c1c1_generated_d3746014.png",
  reSolidworks: "https://media.base44.com/images/public/6a44d2347ed5692671cd034a/3266e2212_generated_3d9e6073.png",
  powerShell: "https://media.base44.com/images/public/6a44d2347ed5692671cd034a/afafcdcb5_generated_fb48982d.png",
  cyborg3d: "https://media.base44.com/images/public/6a44d2347ed5692671cd034a/20de6bf4c_generated_98f710de.png",
  scanToCad: "https://media.base44.com/images/public/6a44d2347ed5692671cd034a/7adfec629_generated_e693ea28.png",
  freeform: "https://media.base44.com/images/public/6a44d2347ed5692671cd034a/3f181ef83_generated_6c501598.png",
  topology: "https://media.base44.com/images/public/6a44d2347ed5692671cd034a/3101e06ea_generated_5e3a0aa4.png",
  industrial: "https://media.base44.com/images/public/6a44d2347ed5692671cd034a/a940f4d16_generated_d2a33b31.png",
};

export const PRODUCTS = [
  {
    id: "re-studio",
    name: "Power Surfacing RE Studio",
    shortName: "RE Studio",
    tagline: "Flagship standalone reverse-engineering software",
    description: "The most advanced standalone reverse-engineering software for scan, mesh, STL/OBJ, sculpted, and polygonal geometry. Convert 3D scan data, mesh files, and sculpted models into precision CAD surfaces.",
    image: IMAGES.reStudio,
    path: "/products/re-studio",
    platform: "Standalone",
    category: "Reverse Engineering",
    features: [
      "Scan-to-CAD conversion",
      "Mesh-to-CAD workflows",
      "STL and OBJ file import",
      "Sculpted mesh to CAD",
      "Automatic surface fitting",
      "NURBS output",
      "Point cloud processing",
      "Mesh cleanup and repair",
    ],
    useCases: [
      "Converting 3D scan data to editable CAD models",
      "Rebuilding legacy parts from physical scans",
      "Converting ZBrush and sculpted meshes to NURBS",
      "Processing STL/OBJ files for manufacturing",
      "Topology optimization output to CAD",
      "Quality inspection and as-built documentation",
    ],
    whoIsItFor: [
      "Reverse engineers and scan technicians",
      "Product designers working with 3D scan data",
      "Manufacturing engineers converting mesh to CAD",
      "Artists converting sculpted models to production geometry",
      "Quality assurance teams needing as-built CAD models",
    ],
    benefits: [
      "Fastest scan-to-CAD workflow available",
      "Handles complex organic and freeform geometry",
      "Produces clean, manufacturing-ready NURBS surfaces",
      "Works with all major 3D scanner and mesh formats",
      "No SOLIDWORKS license required",
    ],
  },
  {
    id: "studio",
    name: "Power Surfacing Studio",
    shortName: "Studio",
    tagline: "Standalone CAD design software",
    description: "Complete standalone CAD design software with dimension-driven sketching, feature-based modeling, surfacing, solids, freeform Sub-D design, and NURBS/CAD output.",
    image: IMAGES.studio,
    path: "/products/studio",
    platform: "Standalone",
    category: "CAD Design",
    features: [
      "Dimension-driven sketching",
      "Feature-based modeling",
      "Surfacing and solid modeling",
      "Freeform Sub-D design",
      "NURBS/CAD output",
      "Parametric constraints",
      "Construction history",
      "Multi-format export",
    ],
    useCases: [
      "Creating complex freeform product designs",
      "Dimension-driven mechanical part design",
      "Combining organic and prismatic geometry",
      "Industrial design concept to production",
      "Consumer product development",
      "Automotive and aerospace surfacing",
    ],
    whoIsItFor: [
      "Industrial designers",
      "Product designers",
      "Mechanical engineers",
      "Freelance CAD professionals",
      "Design studios and consultancies",
    ],
    benefits: [
      "Complete CAD design in one standalone application",
      "No third-party CAD license required",
      "Sub-D freedom with engineering precision",
      "Dimension-driven control for manufacturing accuracy",
      "Feature-based modeling with construction history",
    ],
  },
  {
    id: "solidworks",
    name: "Power Surfacing for SOLIDWORKS",
    shortName: "for SOLIDWORKS",
    tagline: "Freeform Sub-D and Class A surfacing inside SOLIDWORKS",
    description: "Add freeform Sub-D subdivision surface modeling and Class A surfacing directly inside your SOLIDWORKS environment. Create organic, flowing surfaces alongside your existing SOLIDWORKS models.",
    image: IMAGES.solidworks,
    path: "/products/solidworks",
    platform: "SOLIDWORKS Add-in",
    category: "Sub-D Design",
    features: [
      "Sub-D subdivision surface modeling",
      "Class A surface quality",
      "Integrated SOLIDWORKS feature tree",
      "Direct SOLIDWORKS solid body output",
      "Crease and edge control",
      "Symmetry tools",
      "Surface continuity control",
      "Real-time preview",
    ],
    useCases: [
      "Adding organic surfaces to mechanical assemblies",
      "Consumer product design in SOLIDWORKS",
      "Automotive interior and exterior surfacing",
      "Medical device enclosures and ergonomic shapes",
      "Sporting goods and wearable product design",
      "Industrial design within SOLIDWORKS workflows",
    ],
    whoIsItFor: [
      "SOLIDWORKS users needing freeform surfacing",
      "Product designers working in SOLIDWORKS",
      "Industrial designers in SOLIDWORKS environments",
      "Engineering teams with SOLIDWORKS standardization",
    ],
    benefits: [
      "Works inside your existing SOLIDWORKS environment",
      "No separate application or file conversion needed",
      "Output appears directly in the SOLIDWORKS feature tree",
      "Combine Sub-D with standard SOLIDWORKS features",
      "Maintain your existing SOLIDWORKS workflows",
    ],
  },
  {
    id: "re-solidworks",
    name: "Power Surfacing RE for SOLIDWORKS",
    shortName: "RE for SOLIDWORKS",
    tagline: "Reverse engineering scan and mesh data inside SOLIDWORKS",
    description: "Perform reverse engineering of scan and mesh data directly inside SOLIDWORKS. Import scans, meshes, STL, and OBJ files and convert them to SOLIDWORKS solid and surface bodies.",
    image: IMAGES.reSolidworks,
    path: "/products/re-solidworks",
    platform: "SOLIDWORKS Add-in",
    category: "Reverse Engineering",
    features: [
      "Import STL, OBJ, and mesh data",
      "Mesh alignment and registration",
      "Surface fitting to scan data",
      "Direct SOLIDWORKS body output",
      "Mesh cleanup and decimation",
      "Automatic and guided surfacing",
      "Deviation analysis",
      "Feature tree integration",
    ],
    useCases: [
      "Reverse engineering scanned parts in SOLIDWORKS",
      "Importing and converting legacy mesh data",
      "As-built documentation from 3D scans",
      "Quality inspection comparing scan to CAD",
      "Converting competitor parts for design reference",
      "Rebuilding parts without original CAD data",
    ],
    whoIsItFor: [
      "SOLIDWORKS users who need reverse engineering",
      "Engineers working with 3D scanner data",
      "Quality teams comparing scans to CAD models",
      "Manufacturing engineers rebuilding legacy parts",
    ],
    benefits: [
      "Reverse engineer directly inside SOLIDWORKS",
      "No separate reverse engineering application needed",
      "Output integrates with SOLIDWORKS feature tree",
      "Leverage existing SOLIDWORKS skills and workflows",
      "Seamless fit with SOLIDWORKS assemblies",
    ],
  },
  {
    id: "power-shell",
    name: "Power Shell for SOLIDWORKS",
    shortName: "Power Shell",
    tagline: "Shelling and thickening difficult SOLIDWORKS geometry",
    description: "Solve challenging shelling and thickening operations on complex SOLIDWORKS geometry that standard SOLIDWORKS tools cannot handle.",
    image: IMAGES.powerShell,
    path: "/products/power-shell",
    platform: "SOLIDWORKS Add-in",
    category: "Shelling",
    features: [
      "Advanced shelling algorithms",
      "Complex geometry thickening",
      "Variable wall thickness",
      "Open and closed shelling",
      "Multi-body support",
      "Feature tree integration",
      "Real-time preview",
      "Handles difficult geometry",
    ],
    useCases: [
      "Shelling complex imported geometry",
      "Thickening surface bodies for manufacturing",
      "Creating uniform wall thickness on organic shapes",
      "Shelling models that fail with standard SOLIDWORKS Shell",
      "Preparing designs for injection molding",
      "Converting surface models to solid shells",
    ],
    whoIsItFor: [
      "SOLIDWORKS users with complex shelling needs",
      "Manufacturing engineers preparing for injection molding",
      "Product designers with organic geometry",
      "Engineers working with imported geometry",
    ],
    benefits: [
      "Succeeds where SOLIDWORKS Shell fails",
      "Handles complex and organic geometry",
      "Direct integration with SOLIDWORKS feature tree",
      "Fast and reliable shelling operations",
      "No workarounds or model simplification needed",
    ],
  },
];

export const WORKFLOWS = [
  { id: "reverse-engineering", name: "Reverse Engineering", path: "/workflows/reverse-engineering", image: IMAGES.reStudio, description: "Convert physical objects and 3D scans into editable CAD geometry using advanced reverse engineering workflows." },
  { id: "scan-to-cad", name: "Scan-to-CAD", path: "/workflows/scan-to-cad", image: IMAGES.scanToCad, description: "Transform raw 3D scan data from any scanner into clean, manufacturing-ready CAD surfaces and solids." },
  { id: "mesh-to-cad", name: "Mesh-to-CAD", path: "/workflows/mesh-to-cad", image: IMAGES.scanToCad, description: "Convert triangulated mesh data into smooth NURBS surfaces and solid CAD models." },
  { id: "stl-obj-to-cad", name: "STL/OBJ to CAD", path: "/workflows/stl-obj-to-cad", image: IMAGES.reSolidworks, description: "Import STL and OBJ files and convert them into editable, parametric CAD geometry." },
  { id: "sculpted-mesh-to-cad", name: "ZBrush / Sculpted Mesh to CAD", path: "/workflows/sculpted-mesh-to-cad", image: IMAGES.freeform, description: "Convert ZBrush, Mudbox, and other sculpted mesh models into production-ready NURBS CAD surfaces." },
  { id: "topology-optimization", name: "Topology Optimization to CAD", path: "/workflows/topology-optimization", image: IMAGES.topology, description: "Convert topology optimization output meshes into clean, manufacturable CAD geometry." },
  { id: "dimension-driven-design", name: "Dimension-Driven CAD Design", path: "/workflows/dimension-driven-design", image: IMAGES.studio, description: "Create precisely dimensioned CAD models with parametric sketching and constraint-driven geometry." },
  { id: "feature-based-modeling", name: "Feature-Based Modeling", path: "/workflows/feature-based-modeling", image: IMAGES.studio, description: "Build complex models using feature-based construction history with full editing and rollback capabilities." },
  { id: "surfacing-solid-modeling", name: "Surfacing and Solid Modeling", path: "/workflows/surfacing-solid-modeling", image: IMAGES.solidworks, description: "Combine precision surface modeling with solid modeling for complete product design and manufacturing." },
  { id: "freeform-sub-d", name: "Freeform Sub-D Design", path: "/workflows/freeform-sub-d", image: IMAGES.freeform, description: "Use subdivision surface modeling to create smooth, organic freeform shapes with intuitive control." },
  { id: "industrial-design-solidworks", name: "Industrial Design in SOLIDWORKS", path: "/workflows/industrial-design-solidworks", image: IMAGES.industrial, description: "Create beautiful, ergonomic industrial designs directly inside SOLIDWORKS using Sub-D surfacing." },
  { id: "shelling-thickening", name: "Shelling and Thickening", path: "/workflows/shelling-thickening", image: IMAGES.powerShell, description: "Shell and thicken complex geometry that standard CAD tools cannot handle." },
];

export const CAPABILITIES = [
  { name: "Dimension-Driven Sketching", icon: "Ruler", description: "Precisely control geometry with parametric dimensions, constraints, and relationships." },
  { name: "Feature-Based Modeling", icon: "Layers", description: "Build complex models with a construction history that can be edited and rolled back at any time." },
  { name: "Surfacing & Solids", icon: "Box", description: "Combine surface modeling and solid modeling for complete product design workflows." },
  { name: "Freeform Sub-D Design", icon: "Spline", description: "Create smooth, organic shapes using subdivision surface modeling with intuitive control." },
  { name: "Reverse Engineering", icon: "ScanLine", description: "Convert 3D scans, meshes, and point clouds into editable CAD geometry." },
  { name: "Scan/Mesh-to-CAD", icon: "FileInput", description: "Import and convert STL, OBJ, and mesh files into NURBS surfaces and solid models." },
  { name: "SOLIDWORKS Workflows", icon: "Workflow", description: "Extend SOLIDWORKS with freeform surfacing, reverse engineering, and advanced shelling." },
  { name: "Shelling & Thickening", icon: "Shell", description: "Handle complex shelling and thickening operations that standard tools cannot solve." },
];

export const NAV_ITEMS = [
  {
    label: "Products",
    path: "/products",
    children: [
      { label: "Products Overview", path: "/products" },
      { label: "Power Surfacing RE Studio", path: "/products/re-studio" },
      { label: "Power Surfacing Studio", path: "/products/studio" },
      { label: "Power Surfacing for SOLIDWORKS", path: "/products/solidworks" },
      { label: "Power Surfacing RE for SOLIDWORKS", path: "/products/re-solidworks" },
      { label: "Power Shell for SOLIDWORKS", path: "/products/power-shell" },
      { label: "Product Comparison", path: "/products/comparison" },
    ],
  },
  {
    label: "Workflows",
    path: "/workflows",
    children: [
      { label: "Workflows Overview", path: "/workflows" },
      { label: "Reverse Engineering", path: "/workflows/reverse-engineering" },
      { label: "Scan-to-CAD", path: "/workflows/scan-to-cad" },
      { label: "Mesh-to-CAD", path: "/workflows/mesh-to-cad" },
      { label: "STL/OBJ to CAD", path: "/workflows/stl-obj-to-cad" },
      { label: "ZBrush / Sculpted Mesh to CAD", path: "/workflows/sculpted-mesh-to-cad" },
      { label: "Topology Optimization to CAD", path: "/workflows/topology-optimization" },
      { label: "Dimension-Driven CAD Design", path: "/workflows/dimension-driven-design" },
      { label: "Feature-Based Modeling", path: "/workflows/feature-based-modeling" },
      { label: "Surfacing and Solid Modeling", path: "/workflows/surfacing-solid-modeling" },
      { label: "Freeform Sub-D Design", path: "/workflows/freeform-sub-d" },
      { label: "Industrial Design in SOLIDWORKS", path: "/workflows/industrial-design-solidworks" },
      { label: "Shelling and Thickening", path: "/workflows/shelling-thickening" },
    ],
  },
  {
    label: "Technology",
    path: "/technology",
  },
  {
    label: "Resources",
    path: "/resources",
    children: [
      { label: "Resources Overview", path: "/resources" },
      { label: "Video Library", path: "/resources/videos" },
      { label: "Product Demos", path: "/resources/demos" },
      { label: "Tutorials", path: "/resources/tutorials" },
      { label: "Documentation", path: "/resources/documentation" },
      { label: "Release Notes", path: "/resources/release-notes" },
      { label: "FAQ", path: "/resources/faq" },
    ],
  },
  {
    label: "Pricing & Downloads",
    path: "/pricing",
    children: [
      { label: "Trial Downloads", path: "/pricing/trials" },
      { label: "Product Downloads", path: "/pricing/downloads" },
      { label: "Upgrade Information", path: "/pricing/upgrades" },
    ],
  },
  {
    label: "Support",
    path: "/support",
    children: [
      { label: "Support Overview", path: "/support" },
      { label: "Getting Started", path: "/support/getting-started" },
      { label: "Tutorials by Product", path: "/support/tutorials" },
      { label: "Installation & Licensing", path: "/support/installation" },
      { label: "Release Notes", path: "/support/release-notes" },
      { label: "Contact Support", path: "/support/contact" },
    ],
  },
  {
    label: "Contact",
    path: "/contact",
  },
];

export const SAMPLE_VIDEOS = [
  { id: "v1", title: "Power Surfacing RE Studio Overview", product: "Power Surfacing RE Studio", type: "Overview", workflow: "Reverse Engineering", level: "Beginner", duration: "12:30", thumbnail: IMAGES.reStudio },
  { id: "v2", title: "Scan-to-CAD Complete Workflow", product: "Power Surfacing RE Studio", type: "Demo", workflow: "Scan-to-CAD", level: "Intermediate", duration: "18:45", thumbnail: IMAGES.scanToCad },
  { id: "v3", title: "Power Surfacing Studio Getting Started", product: "Power Surfacing Studio", type: "Tutorial", workflow: "Dimension-Driven CAD Design", level: "Beginner", duration: "15:20", thumbnail: IMAGES.studio },
  { id: "v4", title: "Freeform Sub-D Design Techniques", product: "Power Surfacing for SOLIDWORKS", type: "Tutorial", workflow: "Freeform Sub-D Design", level: "Intermediate", duration: "22:10", thumbnail: IMAGES.freeform },
  { id: "v5", title: "STL to CAD Conversion", product: "Power Surfacing RE Studio", type: "Demo", workflow: "STL/OBJ to CAD", level: "Beginner", duration: "10:15", thumbnail: IMAGES.reSolidworks },
  { id: "v6", title: "Class A Surfacing in SOLIDWORKS", product: "Power Surfacing for SOLIDWORKS", type: "Tutorial", workflow: "Industrial Design in SOLIDWORKS", level: "Advanced", duration: "25:30", thumbnail: IMAGES.solidworks },
  { id: "v7", title: "Mesh-to-CAD Best Practices", product: "Power Surfacing RE Studio", type: "Demo", workflow: "Mesh-to-CAD", level: "Intermediate", duration: "14:50", thumbnail: IMAGES.scanToCad },
  { id: "v8", title: "Power Shell Shelling Tutorial", product: "Power Shell for SOLIDWORKS", type: "Tutorial", workflow: "Shelling and Thickening", level: "Beginner", duration: "8:20", thumbnail: IMAGES.powerShell },
  { id: "v9", title: "ZBrush Model to NURBS CAD", product: "Power Surfacing RE Studio", type: "Demo", workflow: "ZBrush / Sculpted Mesh to CAD", level: "Advanced", duration: "20:00", thumbnail: IMAGES.freeform },
  { id: "v10", title: "Topology Optimization to Solid CAD", product: "Power Surfacing RE Studio", type: "Demo", workflow: "Topology Optimization to CAD", level: "Advanced", duration: "16:40", thumbnail: IMAGES.topology },
  { id: "v11", title: "RE for SOLIDWORKS Quick Start", product: "Power Surfacing RE for SOLIDWORKS", type: "Tutorial", workflow: "Reverse Engineering", level: "Beginner", duration: "11:30", thumbnail: IMAGES.reSolidworks },
  { id: "v12", title: "Feature-Based Modeling Deep Dive", product: "Power Surfacing Studio", type: "Tutorial", workflow: "Feature-Based Modeling", level: "Intermediate", duration: "19:15", thumbnail: IMAGES.studio },
];