// Centralized site data for nPower Software / Power Surfacing

export const IMAGES = {
  hero: "https://media.base44.com/images/public/6a44d2347ed5692671cd034a/405ae3473_generated_7bdd1c95.png",
  reStudio: "/assets/product-re-studio.png",
  studio: "/assets/product-studio.png",
  solidworks: "/assets/product-solidworks.png",
  reSolidworks: "/assets/product-re-solidworks.png",
  powerShell: "/assets/product-power-shell.png",
  solidsSharp: "https://media.base44.com/images/public/6a44d2347ed5692671cd034a/d0b31060d_generated_image.png",
  scanToCad: "https://media.base44.com/images/public/6a44d2347ed5692671cd034a/7adfec629_generated_e693ea28.png",
  freeform: "https://media.base44.com/images/public/6a44d2347ed5692671cd034a/3f181ef83_generated_6c501598.png",
  topology: "https://media.base44.com/images/public/6a44d2347ed5692671cd034a/3101e06ea_generated_5e3a0aa4.png",
  industrial: "https://media.base44.com/images/public/6a44d2347ed5692671cd034a/a940f4d16_generated_d2a33b31.png",
};

export const PRODUCTS = [
  {
    id: "power-surfacing-re-studio",
    name: "Power Surfacing RE Studio",
    pageTitle: "Power Surfacing RE Studio | Scan-to-CAD Reverse Engineering",
    pageDescription: "Convert 3D scan meshes, sculpted meshes, stl meshes and CAD meshes into editable CAD surfaces and solids using reverse engineering, dimension-driven sketching, feature modeling and Sub-D tools.",
    shortName: "RE Studio",
    tagline: "Standalone reverse-engineering software for scanned and sculpted meshes",
    description: "The most advanced standalone reverse-engineering software for scanned meshes, ZBrush sculpts, and polygonal geometry. Power Surfacing RE Studio captures very fine surface detail with a highly automated workflow, converting complex meshes into high-quality NURBS surfaces in a matter of minutes. It includes the complete Power Surfacing Studio toolset, adding reverse-engineering capabilities on top of full hybrid Sub-D / parametric NURBS modeling.",
    image: IMAGES.reStudio,
    path: "/products/power-surfacing-re-studio",
    testimonialsPath: "/customers/power-surfacing-re-studio",
    platform: "Standalone",
    category: "Reverse Engineering",
    inputs: ["STL", "OBJ meshes", "Point clouds", "Sculpted meshes"],
    outputs: ["STEP", "IGES", "SAT", "NURBS solids & surfaces", "Direct SOLIDWORKS export"],
    pricing: {
      options: [
        { label: "Perpetual License", price: "$6,995", originalPrice: "$8,995", badge: "Intro pricing through June 2027", detail: "One-time purchase, yours forever" },
        { label: "Annual Maintenance", price: "$1,795", period: "/year", detail: "Updates and support for perpetual licenses" },
        { label: "Annual Subscription", price: "$2,995", originalPrice: "$3,995", period: "/first year", badge: "First-year intro price", detail: "$3,995/year thereafter — includes updates and support" },
      ],
      note: "Introductory perpetual pricing available through June 2027. Choose a perpetual license with optional maintenance, or a lower-upfront annual subscription.",
    },
    testimonials: [
      { quote: "RE Studio converted a scan that took us days in other tools into clean NURBS surfaces in under an hour. The Quad Wrap retopology is remarkable.", name: "David M.", title: "Reverse Engineering Specialist, Aerospace Supplier" },
      { quote: "We digitize clay models for consumer products, and the fine detail capture is the best we've seen at any price point.", name: "Sarah K.", title: "Design Director, Product Studio" },
      { quote: "The STEP export drops straight into our downstream CAD with no cleanup. It just works.", name: "James T.", title: "Mechanical Engineer, Medical Devices" },
    ],
    features: [
      "Includes everything in Power Surfacing Studio — full Sub-D and parametric NURBS modeling",
      "Import of STL and Wavefront OBJ files",
      "Automatic Quad Wrap retopology that follows curvature flow",
      "Automatic identification and parameterization of analytic shapes (planes, cylinders, spheres, cones)",
      "Section a scanned mesh and reconstruct sketch geometry — lines, circles, arcs, and freeform curves — manually or automatically",
      "Segment the mesh into face groups or regions for analytic and organic surfaces",
      "Graphical deviation overlay measures accuracy against the original mesh",
      "Reconstruction using either solids or surfaces for hybrid organic and mechanical parts",
      "Shrink Wrap tool adds fine detail without adding polygons",
      "Mesh repair, smoothing, and hole-filling tools",
      "Sub-D to Brep NURBS conversion with G2 edge continuity",
      "Advanced shelling and variable wall thickness",
      "Export to STEP, IGES, and SAT formats",
      "Export directly into SOLIDWORKS, creating a corresponding feature tree with an editable parametric history",
      "SOLIDWORKS Topology Study mesh conversion",
      "Point cloud (OBJ) import and processing",
    ],
    useCases: [
      "Reverse engineering scanned meshes into accurate, editable NURBS geometry",
      "Converting ZBrush and other sculpted meshes into CAD-ready surfaces",
      "Rebuilding human forms, animal shapes, and other organic geometry",
      "Capturing fine surface detail on jewelry, cutlery, and consumer products",
      "Digitizing clay models and physical prototypes for CAD",
      "Converting SOLIDWORKS Topology Study output into usable solid geometry",
    ],
    whoIsItFor: [
      "Reverse engineers and 3D scan technicians",
      "Industrial and product designers working with organic shapes",
      "Medical, dental, and prosthetics professionals working from scans",
      "Artists digitizing sculptures and fine art pieces",
      "Toy, character, and game controller designers",
      "Jewelry, cutlery, and consumer goods designers",
      "Engineers digitizing clay models and physical prototypes",
    ],
    benefits: [
      "Aggressively priced compared to other reverse-engineering solutions",
      "Captures very fine detail on scanned and sculpted meshes",
      "Highly automated workflow processes complex meshes in minutes",
      "Produces high-quality, G2-continuous NURBS surfaces",
      "Exports to STEP, IGES, and SAT for any downstream CAD system",
    ],
    detail: {
      definition: "Power Surfacing RE Studio is a standalone Windows reverse-engineering application for engineers, designers, and scan technicians that converts 3D scans, STL/OBJ meshes, sculpted meshes, and point clouds into editable, high-quality NURBS CAD geometry — no third-party CAD license required.",
      overviewYoutubeId: "yZr-buzOCGc",
      quickFacts: [
        { label: "Runs as", value: "Standalone Windows application — no CAD license required" },
        { label: "Best for", value: "Reverse engineering scanned and sculpted meshes" },
        { label: "Modeling method", value: "Mesh to Sub-D to NURBS" },
        { label: "Includes", value: "All of the functionality of Power Surfacing Studio" },
        { label: "Current release", value: "See Release Notes for the latest version" },
        { label: "Operating system", value: "Windows 10 / 11, 64-bit" },
        { label: "Trial", value: "Free trial — install and choose the evaluation option at launch" },
      ],
      problem: {
        paragraphs: [
          "Do you have scanned meshes from mechanical, organic, or meshes with mixed mechanical and organic components? Meshes from 3D scanners, sculpting programs like ZBrush, FEA tools, 3D printer files, and online model databases aren't editable CAD. Existing reverse-engineering products specialize in precise prismatic parts, leave organic and freeform shapes extremely problematic, and usually require an expensive CAD platform underneath them.",
          "Power Surfacing RE Studio solves this in one standalone application. Its patent-pending technology captures the fine details of a scanned mesh — a level of accuracy that would normally create extremely large models or fail on memory — and uniquely follows the curvature and flow lines of the mesh so creases, ridges, and gullies aren't washed out in the conversion to NURBS. For more mechanical parts, RE Studio extracts curves directly from the mesh and reconstructs feature-based solids from them — and because it handles hybrid mixed mechanical and organic geometry in one model, it's equally at home on precise prismatic parts, freeform shapes, and everything in between. It includes the complete Power Surfacing Studio toolset, so once the shape is captured you can keep modifying and evolving the design with full hybrid Sub-D / parametric NURBS modeling." ,
        ],
      },
      workflowSteps: [
        { title: "Import a reference mesh", description: "Bring in a 3D scan, STL/OBJ mesh, point cloud (OBJ), sculpted mesh, or 3D printer file — including SOLIDWORKS Topology Study output." },
        { title: "Repair and prepare", description: "Clean up messy imports with Mesh Smooth, Mesh Offset, and hole-filling, and use automated tools to find and fix scan anomalies like tears, rips, holes, and overlaps." },
        { title: "Identify and extract analytic geometry", description: "Identification and extraction of analytic geometry — planes, cylinders, cones, and spheres — from regions of the mesh." },
        { title: "Section the mesh into sketches", description: "Section the scanned mesh to reconstruct sketch geometry — lines, circles, arcs, and freeform curves — manually or automatically, then build corresponding mechanical geometry from those sketches." },
        { title: "Retopologize", description: "Run automatic Quad Wrap retopology — accurate, fast, curvature-following quad topology that automatically closes most open edges — or draw faces constrained to the reference mesh." },
        { title: "Capture fine detail", description: "Interpolate or 'vacuum seal' with Shrink Wrap (with automatic self-intersection fixes) to closely approximate the mesh, and verify accuracy with the Distance display." },
        { title: "Convert and export", description: "Convert to G2-continuous NURBS surfaces and solids, refine with the full Power Surfacing Studio toolset, and export STEP, IGES, or SAT for any downstream CAD system — or export directly into SOLIDWORKS, creating a corresponding feature tree with an editable parametric history." },
      ],
      capabilities: [
        { name: "Quad Wrap Auto-Retopology", benefit: "Complex meshes converted in minutes, not days.", technical: "Automatically retopologizes the mesh with clean quad flow, following curvature, and automatically detects and closes most open edges." },
        { name: "Shrink Wrap Detail Capture", benefit: "Fine surface detail without model bloat.", technical: "'Vacuum seals' the Sub-D surface to the reference mesh, automatically checking for and fixing self-intersections; patent-pending curvature-driven knot density keeps model size optimal." },
        { name: "Follows Curvature & Flow Lines", benefit: "Creases and ridges survive the conversion.", technical: "Uniquely follows the flow lines and features of the scanned mesh when converting to NURBS, so sharp features aren't washed out." },
        { name: "Anomaly Detection & Repair", benefit: "Restore damaged or incomplete scans.", technical: "Automated tools identify problem areas — tears, rips, holes, overlaps, worn edges — and fix them with minimal effort." },
        { name: "Mesh Sectioning & Sketch Reconstruction", benefit: "Rebuild design intent as real sketch geometry.", technical: "Section a scanned mesh and reconstruct sketch geometry both manually and automatically — the sectioning process creates lines, circles, arcs, and freeform curves." },
        { name: "Curve Extraction & Feature-Based Reconstruction", benefit: "Reverse engineer mechanical parts as real feature-based solids.", technical: "Extract curves directly from the mesh and use them to reconstruct feature-based solids — capturing mechanical design intent, with full support for hybrid mixed mechanical and organic parts." },
        { name: "Mesh Segmentation into Regions", benefit: "The right surface type for every part of the mesh.", technical: "Segments the mesh into face groups or regions corresponding to analytic surfaces — planes, cylinders, cones, and spheres — as well as more organic surfaces." },
        { name: "Graphical Deviation Analysis", benefit: "See exactly how accurate the reconstruction is.", technical: "Measurement technology shows deviation from the original mesh in a graphical overlay, so accuracy is verified visually across the entire part." },
        { name: "Solid & Surface Reconstruction", benefit: "An excellent choice for hybrid organic and mechanical parts.", technical: "Supports reconstruction using either solids or surfaces, combining precise analytic geometry with freeform organic shapes in one model." },
        { name: "Full Studio Toolset Included", benefit: "Complete hybrid modeling at no extra cost.", technical: "Everything in Power Surfacing Studio — dimension-driven sketching, feature-based history, Class A conversion, advanced shelling — plus STEP/IGES/SAT export." },
      ],
      compatibility: {
        requirements: [
          { label: "Operating System", value: "Windows 10 or Windows 11, 64-bit — no SOLIDWORKS or other CAD license required" },
          { label: "Processor", value: "2.5 GHz or higher, multi-core Intel or AMD" },
          { label: "Memory (RAM)", value: "8 GB minimum; 16–32 GB recommended for dense scan meshes" },
          { label: "Graphics Card", value: "Dedicated GPU with OpenGL Shader support; 2 GB+ VRAM recommended" },
          { label: "Disk Space", value: "2 GB free space for installation" },
        ],
      },
      examples: [
        { title: "Scan-to-CAD in Under an Hour", description: "A scan that took days in other tools was converted into clean NURBS surfaces in under an hour — with Quad Wrap retopology doing the heavy lifting automatically." },
        { title: "Clay Model Digitizing", description: "Design teams digitize clay models and physical prototypes for consumer products, with the best fine-detail capture they've seen at any price point." },
        { title: "Clean Downstream Export", description: "STEP exports drop straight into downstream CAD with no cleanup — accurate, editable, G2-continuous geometry optimized for the CAD environment." },
        { title: "Organic & Human Forms", description: "Reverse engineer human forms, animal shapes, sculptures, and other freeform representations that prismatic-focused tools can't handle." },
      ],
      industries: ["Industrial Design", "Ergonomics", "Sporting Goods & Clothing", "Toys", "Character Design", "Medical, Dental & Prosthetics", "Re-purposing Existing Designs", "Handheld Devices", "Power Tools", "Jewelry", "Cutlery", "Furniture", "Automotive", "Art", "Clay Model Digitizing", "Cosmetics"],
      faq: [
        { q: "Do I need SOLIDWORKS or another CAD system?", a: "No. Power Surfacing RE Studio is a complete standalone Windows application — no third-party CAD license is required. Export STEP, IGES, or SAT for any downstream CAD system, or export directly into SOLIDWORKS with a corresponding feature tree containing an editable parametric history." },
        { q: "What meshes can I reverse engineer?", a: "3D scanner output, STL and OBJ meshes, point clouds (OBJ), ZBrush and other sculpted meshes, FEA meshes, 3D printer files, and SOLIDWORKS Topology Study output." },
        { q: "How is it different from Power Surfacing Studio?", a: "RE Studio includes the complete Power Surfacing Studio toolset and adds the reverse-engineering tools: reference meshes, Quad Wrap, Shrink Wrap, mesh repair, Distance display, and STL/point-cloud import." },
        { q: "How is it different from Power Surfacing RE for SOLIDWORKS?", a: "The reverse-engineering toolset is equivalent, but RE Studio runs standalone and exports STEP/IGES/SAT or directly into SOLIDWORKS with an editable feature tree, while the add-in runs inside SOLIDWORKS and converts directly to native SOLIDWORKS bodies." },
        { q: "How accurate are the converted surfaces?", a: "Patent-pending technology follows the curvature and flow lines of the mesh and uses curvature-driven surface knot density, capturing fine detail to your desired accuracy without bloating the model. The Distance display lets you measure the approximation against the reference mesh." },
        { q: "Is there a free trial?", a: "Yes. Download the installer and choose the trial/evaluation option when you launch the application." },
      ],
      faqLink: "/resources/faq/studio",
    },
  },
  {
    id: "power-surfacing-studio",
    name: "Power Surfacing Studio",
    shortName: "Studio",
    tagline: "Standalone freeform Sub-D and Class A surfacing design software",
    description: "Model complex, aesthetically pleasing Class A surfaces with the ease of digital clay. Power Surfacing Studio delivers hybrid Sub-D / parametric NURBS modeling — its strength isn't just freeform organic design; it's equally suited to mechanical parts and the hybrid mechanical/organic parts common in industrial design — no third-party CAD license required.",
    image: IMAGES.studio,
    path: "/products/power-surfacing-studio",
    testimonialsPath: "/customers/power-surfacing-studio",
    platform: "Standalone",
    category: "CAD Design",
    inputs: ["Sketches", "OBJ / FBX meshes", "STEP files (NURBS CAD)", "Primitive shapes"],
    outputs: ["Class A NURBS surfaces", "Solid bodies", "STEP / IGES / SAT", "Direct SOLIDWORKS export"],
    pricing: {
      options: [
        { label: "Perpetual License", price: "$1,995", originalPrice: "$3,495", badge: "Intro pricing through June 2027", detail: "One-time purchase, yours forever" },
        { label: "Annual Maintenance", price: "$695", period: "/year", detail: "Updates and support for perpetual licenses" },
        { label: "Annual Subscription", price: "$995", originalPrice: "$1,395", period: "/first year", badge: "First-year intro price", detail: "$1,395/year thereafter — includes updates and support" },
      ],
      note: "Introductory pricing available through June 2027. Choose a perpetual license with optional maintenance, or a lower-upfront annual subscription.",
    },
    testimonials: [
      { quote: "Studio gives me true Class A surfaces with the freedom of digital clay. I moved my entire concept workflow into it.", name: "Elena R.", title: "Industrial Designer, Consumer Electronics" },
      { quote: "The mix of dimension-driven sketching and Sub-D freeform modeling is something no other standalone tool offers at this price.", name: "Marcus B.", title: "Freelance Product Designer" },
      { quote: "We prototype bottle and handle designs in hours instead of days. Clients notice the surface quality immediately.", name: "Priya S.", title: "Principal, Design Consultancy" },
    ],
    features: [
      "All of the features of Power Surfacing for SOLIDWORKS — the complete Sub-D modeling toolset",
      "Dimension-driven 2D and 3D sketching",
      "Parametric, feature-based modeling with full construction history",
      "Advanced surface construction using Sub-D or sweeping, lofting, and blending",
      "Constrain Sub-D geometry to existing analytic and freeform geometry with tangency and curvature continuity",
      "Export directly into SOLIDWORKS, creating a corresponding feature tree with an editable parametric history",
      "Primitive shapes: box, cylinder, torus, and more",
      "Dynamic push-pull editing with constrained editing and soft selection",
      "Core tools: Extrude, Inset, Insert Loops, Bridge",
      "Mirror, Bend, Edge Weighting, and Subdivide",
      "Advanced tools: Extend, Edge Extrude, Insert Edge, Shell, Thicken",
      "Import of OBJ and FBX meshes from Modo, 3ds Max, and Maya",
      "Import of NURBS-based STEP files from CAD systems",
      "Conversion to Class A NURBS surface or solid bodies",
      "Dimension-driven, feature-based construction history",
    ],
    useCases: [
      "Designing complex freeform, organic industrial design shapes",
      "Designing mechanical parts and hybrid mechanical/organic parts",
      "Modeling consumer products like bottles, handles, and enclosures",
      "Creating jewelry, cutlery, and character designs with Sub-D precision",
      "Combining dimension-driven sketches with freeform Sub-D surfaces",
      "Building Class A automotive and sporting goods surfaces",
      "Prototyping product concepts before committing to CAD detail",
    ],
    whoIsItFor: [
      "Industrial designers",
      "Product designers",
      "Toy, character, and consumer goods designers",
      "Freelance CAD professionals",
      "Design studios and consultancies",
    ],
    benefits: [
      "Unifies Sub-D freeform modeling and NURBS precision in one application",
      "Manipulating parts is as simple as modeling with clay",
      "Dimension-driven Sub-D modeling for repeatable, precise design",
      "No third-party CAD license required",
      "Full feature-based construction history for easy revisions",
    ],
    detail: {
      definition: "Power Surfacing Studio is a standalone Windows application for industrial and product designers that combines freeform Sub-D (subdivision surface) modeling with dimension-driven, feature-based NURBS design — equally at home on organic shapes, mechanical parts, and hybrid mechanical/organic industrial designs — with no third-party CAD license required.",
      overviewYoutubeId: "tVl9xQwSiCE",
      quickFacts: [
        { label: "Runs as", value: "Standalone Windows application — no CAD license required" },
        { label: "Best for", value: "Freeform, mechanical, and hybrid mechanical/organic design" },
        { label: "Modeling method", value: "Hybrid Sub-D / parametric NURBS" },
        { label: "Current release", value: "See Release Notes for the latest version" },
        { label: "Operating system", value: "Windows 10 / 11, 64-bit" },
        { label: "Trial", value: "Free trial — install and choose the evaluation option at launch" },
      ],
      problem: {
        paragraphs: [
          "Traditional CAD excels at parametric, prismatic engineering — but creating freeform, organic shapes means fighting to patch sets of trimmed surfaces together. Achieving aesthetically pleasing Class A surfaces with tangent and curvature continuity is slow, and dedicated surfacing packages typically require an expensive CAD platform underneath them.",
          "Neither Sub-D modeling nor NURBS modeling can effectively solve all 3D design problems alone. Sub-D are great at producing and modifying complex freeform, organic shapes with smooth surfaces; NURBS are good at combining shapes via Boolean and feature operations, and refining them with filleting, blending, and face editing. Power Surfacing Studio unifies the two in a single standalone application — manipulating parts becomes as simple as modeling with clay, while dimension-driven sketches and a feature-based construction history keep the design precise and repeatable.",
        ],
      },
      workflowSteps: [
        { title: "Start a design", description: "Begin from a primitive shape (box, cylinder, torus), a dimension-driven sketch, an imported OBJ/FBX mesh from Modo, 3ds Max, or Maya — or a NURBS-based STEP file imported from your CAD system." },
        { title: "Sculpt like clay", description: "Shape the model with dynamic push-pull editing, constrained editing, and soft selection — direct, intuitive manipulation of the Sub-D control cage." },
        { title: "Drive the design with dimensions", description: "Editing dimensions and feature parameters updates downstream features and constrained Sub-D geometry — the freeform shape stays connected to your parametric, feature-based history." },
        { title: "Convert to NURBS", description: "Sub-D surfaces and solids are converted to Class A NURBS geometry using IntegrityWare's patented conversion process, with tangent and curvature continuity." },
        { title: "Export manufacturing-ready CAD", description: "Export STEP, IGES, or SAT files for any downstream CAD or manufacturing workflow — or export directly into SOLIDWORKS, creating a corresponding feature tree with an editable parametric history." },
      ],
      capabilities: [
        { name: "Standalone — No CAD License", benefit: "Complete design environment in one application.", technical: "Includes all of the features of Power Surfacing for SOLIDWORKS with no third-party CAD platform required — a fraction of the cost of a CAD seat plus a surfacing add-in." },
        { name: "Clay-Like Push-Pull Editing", benefit: "Model complex shapes as easily as sculpting clay.", technical: "Dynamic push-pull editing with constrained editing and soft selection on the subdivision surface control cage — built on the Catmull-Clark subdivision algorithms popularized by Pixar." },
        { name: "Dimension-Driven 2D & 3D Sketching", benefit: "Freeform shapes that respond to parametric changes.", technical: "Dimension-driven, constraint-based 2D and 3D sketches drive the geometry — combined with parametric, feature-based modeling, the design updates with feature-history modifications." },
        { name: "Advanced Surface Construction", benefit: "Production-quality Class A surfaces, built your way.", technical: "Construct surfaces using Sub-D or classic sweeping, lofting, and blending, then convert to Class A NURBS surfaces or solid bodies with tangent and curvature (G2) continuity." },
        { name: "Constrain Sub-D to Existing Geometry", benefit: "Freeform shapes that blend seamlessly into your design.", technical: "Constrain Sub-D geometry to existing analytic and freeform geometry, with tangency and curvature continuity possible at the connection." },
        { name: "Mesh & CAD Import", benefit: "Bring in work from polygonal modeling tools and CAD systems.", technical: "Imports OBJ and FBX meshes from Modo, 3ds Max, Maya, and others, plus NURBS-based STEP files from CAD systems. For STL, scan, and sculpted meshes, see Power Surfacing RE Studio." },
        { name: "Advanced Shelling & Thickening", benefit: "Prepare parts for manufacturing in the same tool.", technical: "Built-in Shell and Thicken tools handle complex, organic geometry that standard CAD shelling commands fail on." },
      ],
      compatibility: {
        requirements: [
          { label: "Operating System", value: "Windows 10 or Windows 11, 64-bit — no SOLIDWORKS or other CAD license required" },
          { label: "Processor", value: "2.5 GHz or higher, multi-core Intel or AMD" },
          { label: "Memory (RAM)", value: "8 GB minimum; 16 GB recommended" },
          { label: "Graphics Card", value: "Dedicated GPU with OpenGL Shader support; 2 GB+ VRAM recommended" },
          { label: "Disk Space", value: "2 GB free space for installation" },
        ],
      },
      examples: [
        { title: "Proven Power Surfacing Technology", description: "Studio is built on the same award-winning Sub-D-to-NURBS technology that won the TenLinks Best of Show gold medal at SOLIDWORKS World — now available without a CAD license." },
        { title: "Consumer Product Concepts in Hours", description: "Design studios prototype bottles, handles, and enclosures in hours instead of days, with clients noticing the Class A surface quality immediately." },
        { title: "Concept-to-CAD Workflow", description: "Move a concept from freeform sculpt to dimension-driven, feature-based model in one application, then export STEP/IGES/SAT for engineering." },
        { title: "Jewelry, Cutlery & Character Design", description: "Sub-D precision handles fine decorative detail and smooth organic transitions that are impractical to build with patched trimmed surfaces." },
      ],
      industries: ["Industrial Design", "Ergonomics", "Sporting Goods & Clothing", "Toys", "Character Design", "Power Tools & Handheld Devices", "Jewelry", "Cutlery", "Furniture", "Automotive", "Art", "Packaging", "Robotics"],
      faq: [
        { q: "Do I need SOLIDWORKS or another CAD system?", a: "No. Power Surfacing Studio is a complete standalone Windows application — no third-party CAD license is required. Export STEP, IGES, or SAT for any CAD system, or export directly into SOLIDWORKS with a corresponding feature tree containing an editable parametric history." },
        { q: "What file formats can I import?", a: "Studio imports OBJ and FBX meshes from tools like Modo, 3ds Max, and Maya, as well as NURBS-based STEP files from CAD systems. For STL files, 3D scans, and ZBrush sculpts, you need Power Surfacing RE Studio." },
        { q: "How is it different from Power Surfacing for SOLIDWORKS?", a: "Studio includes all of the features of Power Surfacing for SOLIDWORKS and runs standalone — adding dimension-driven 2D and 3D sketching, parametric feature-based modeling, and advanced surface construction using Sub-D or sweeping, lofting, and blending. The add-in runs inside SOLIDWORKS and converts to native SOLIDWORKS bodies." },
        { q: "How is it different from Power Surfacing RE Studio?", a: "RE Studio includes everything in Studio and adds the reverse-engineering toolset: reference meshes, Quad Wrap, Shrink Wrap, mesh repair, and STL/point-cloud import." },
        { q: "Is there a free trial?", a: "Yes. Download the installer and choose the trial/evaluation option when you launch the application." },
      ],
      faqLink: "/resources/faq/studio",
    },
  },
  {
    id: "power-surfacing-solidworks",
    name: "Power Surfacing for SOLIDWORKS",
    shortName: "Power Surfacing",
    tagline: "Freeform Sub-D and Class A surfacing inside SOLIDWORKS",
    description: "Power Surfacing is the industrial design add-in that brings freeform Sub-D surfacing to SOLIDWORKS. Manipulating Power Surfacing parts is as simple as modeling with clay — create complex, aesthetically pleasing Class A surfaces, then convert them directly into SOLIDWORKS solid or surface bodies integrated with your feature tree.",
    image: IMAGES.solidworks,
    path: "/products/power-surfacing-solidworks",
    testimonialsPath: "/customers/solidworks",
    platform: "SOLIDWORKS Add-in",
    category: "Sub-D Design",
    inputs: ["SOLIDWORKS sketches", "OBJ / FBX meshes"],
    outputs: ["SOLIDWORKS solid & surface bodies"],
    pricing: {
      options: [
        { label: "Single Seat License", price: "$2,995", detail: "Perpetual license for one user" },
        { label: "Network License", price: "$3,995", detail: "Floating license shared across your team" },
        { label: "Annual Maintenance", price: "$595", period: "/year", detail: "Updates and support" },
      ],
    },
    testimonials: [
      { quote: "I love your program — for me the Power Surfacing plugin represents the most significant advancement in SOLIDWORKS modelling capability in more than a decade!", name: "James Bevan", title: "Duncan Walton London" },
      { quote: "Power Surfacing has exceeded every one of our expectations for delivering fast results in a dynamic editing environment within SOLIDWORKS. We are such fans of the new plugin.", name: "Raquel Rabago", title: "Tovolo" },
      { quote: "The Sub-D approach to complex shape design is COMPLETELY unlike anything you have EVER been able to do in SOLIDWORKS, and yet it complements SOLIDWORKS so well. Their price point is remarkable given the functionality they are bringing to the table.", name: "Jason Pancoast", title: "CAPINC" },
    ],
    features: [
      "Power Body macro-features that behave like native SOLIDWORKS features",
      "Creation directly from SOLIDWORKS sketches",
      "Import of OBJ and FBX meshes from Modo, 3ds Max, and Maya",
      "Dynamic push-pull editing, soft selection, and mirror/bend tools",
      "Editable and creatable directly from SOLIDWORKS assemblies",
      "Conversion to Class A SOLIDWORKS surface or solid bodies",
      "Full integration with the SOLIDWORKS Feature Tree",
      "Includes Power Shell and Power Thicken at no extra cost",
    ],
    useCases: [
      "Adding organic, freeform surfaces to mechanical assemblies",
      "Consumer product and industrial design inside SOLIDWORKS",
      "Automotive interior, exterior, and sporting goods surfacing",
      "Toy, character, and handheld device design",
      "Editing Power Surface bodies as instances or references across assemblies",
    ],
    whoIsItFor: [
      "SOLIDWORKS users needing freeform surfacing",
      "Industrial designers working inside SOLIDWORKS",
      "Product designers standardized on SOLIDWORKS",
      "Engineering teams designing organic, ergonomic parts",
    ],
    benefits: [
      "Won the TenLinks Best of Show award at SOLIDWORKS World",
      "Backed by an official SOLIDWORKS Gold Partner",
      "Power Body macro-features integrate with the SOLIDWORKS feature tree",
      "Includes Power Shell and Power Thicken at no additional cost",
      "Combines Sub-D freeform design with SOLIDWORKS parametric precision",
    ],
    detail: {
      definition: "Power Surfacing is an award-winning SOLIDWORKS industrial design add-in for engineers and designers that brings freeform Sub-D (subdivision surface) modeling directly into SOLIDWORKS on Windows — sculpt organic shapes like clay and convert them into native Class A solid or surface bodies.",
      overviewYoutubeId: "tVl9xQwSiCE",
      quickFacts: [
        { label: "Runs inside", value: "SOLIDWORKS (64-bit)" },
        { label: "Best for", value: "Freeform and organic product design" },
        { label: "Modeling method", value: "Sub-D to CAD/NURBS" },
        { label: "Current release", value: "Power Surfacing 10.x — see Release Notes" },
        { label: "Operating system", value: "Windows 10 / 11 (64-bit) with SOLIDWORKS 2021 or newer" },
        { label: "Trial", value: "Free trial — install and choose the evaluation option at launch" },
      ],
      problem: {
        paragraphs: [
          "SOLIDWORKS excels at parametric, prismatic engineering — but creating freeform, organic shapes means fighting to patch sets of trimmed surfaces together. Achieving aesthetically pleasing Class A surfaces with tangent and curvature continuity is slow, so many teams avoid surface changes entirely or are forced to use software other than SOLIDWORKS for organic-shaped components.",
          "Neither Sub-D modeling nor NURBS modeling can effectively solve all 3D design problems alone. Sub-D are great at producing and modifying complex freeform, organic shapes with smooth surfaces; NURBS are good at combining shapes via Boolean and feature operations, and refining them with filleting, blending, and face editing. Power Surfacing is a powerful unification of the two — manipulating parts becomes as simple as modeling with clay, while Power Surface objects stay connected to SOLIDWORKS sketches and update with history-tree modifications, providing true dimension-driven Sub-D modeling.",
        ],
      },
      workflowSteps: [
        { title: "Start a Power Body", description: "Begin from a primitive shape (box, cylinder, torus), a SOLIDWORKS sketch, or an imported OBJ/FBX mesh from Modo, 3ds Max, or Maya." },
        { title: "Sculpt like clay", description: "Shape the model with dynamic push-pull editing, constrained editing, and soft selection — direct, intuitive manipulation of the Sub-D control cage." },
        { title: "Refine the topology", description: "Use Extrude, Inset, Insert Loops, Bridge, Mirror, Bend, Edge Weighting, Subdivide, and advanced tools like Extend, Edge Extrude, Shell, and Thicken." },
        { title: "Convert to Class A geometry", description: "Convert the Sub-D model into SOLIDWORKS surface or solid bodies with tangent and curvature continuity." },
        { title: "Keep engineering in SOLIDWORKS", description: "The Power Body is a macro-feature in your feature tree — apply fillets, Booleans, and downstream features, edit from assemblies, and reuse bodies as instances or references." },
      ],
      capabilities: [
        { name: "Power Body Macro-Features", benefit: "Behaves like a native SOLIDWORKS feature.", technical: "Power Bodies live in the feature tree as macro-features, can be created and edited directly from SOLIDWORKS assemblies, and used as instances or references." },
        { name: "Clay-Like Push-Pull Editing", benefit: "Model complex shapes as easily as sculpting clay.", technical: "Dynamic push-pull editing with constrained editing and soft selection on the subdivision surface control cage." },
        { name: "Dimension-Driven Sub-D", benefit: "Freeform shapes that respond to parametric changes.", technical: "Connect Power Surface Sub-D objects directly to SOLIDWORKS sketches and geometry; the Sub-D updates to correspond to history-tree modifications." },
        { name: "Class A Conversion", benefit: "Production-quality surfaces, not just concept models.", technical: "Converts Sub-D geometry into Class A SOLIDWORKS surface or solid bodies with tangent and curvature (G2) continuity." },
        { name: "Mesh Import", benefit: "Bring in work from polygonal modeling tools.", technical: "Imports OBJ and FBX meshes from Modo, 3ds Max, Maya, and others. For STL, scan, ZBrush, and Topology Study meshes, see Power Surfacing RE." },
        { name: "Power Shell & Power Thicken Included", benefit: "Advanced shelling at no extra cost.", technical: "Both add-ins ship free with Power Surfacing, handling shell and thicken operations that native SOLIDWORKS commands fail on." },
      ],
      compatibility: {
        requirements: [
          { label: "SOLIDWORKS Version", value: "SOLIDWORKS 2021 or newer (64-bit) for current releases; older SOLIDWORKS versions supported with matching older product versions" },
          { label: "Operating System", value: "Windows 10 or Windows 11, 64-bit" },
          { label: "Processor", value: "3.3 GHz or higher multi-core Intel or AMD (as recommended by SOLIDWORKS)" },
          { label: "Memory (RAM)", value: "16 GB minimum; 32 GB recommended" },
          { label: "Graphics Card", value: "Certified SOLIDWORKS GPU with OpenGL Shader support and up-to-date drivers" },
        ],
      },
      examples: [
        { title: "TenLinks Best of Show — SOLIDWORKS World", description: "Power Surfacing won the TenLinks Best of Show gold medal at SOLIDWORKS World 2014, with press calling it 'the most significant advancement in SOLIDWORKS modelling capability in more than a decade.'" },
        { title: "Game Controller — GrabCAD 3D Printing Demo", description: "Shuvom Ghose used Power Surfacing to model realistic game controller prototypes for 3D printing in his popular GrabCAD tutorial on consumer product prototyping." },
        { title: "Automotive Surfacing Series", description: "Andy Fulcher of Solid Solutions published a four-part series on using Power Surfacing for automotive applications — Class A body panels and interior surfaces built inside SOLIDWORKS." },
        { title: "Desktop Engineering Editor's Pick", description: "Selected as Desktop Engineering's Editor's Pick of the Week for uniting the disparate paradigms of Sub-D modeling and NURBS-based CAD modeling." },
      ],
      industries: ["Industrial Design", "Ergonomics", "Sporting Goods & Clothing", "Toys", "Character Design", "Power Tools & Handheld Devices", "Jewelry", "Cutlery", "Furniture", "Automotive", "Art", "Packaging", "Robotics"],
      faq: [
        { q: "Do I need a SOLIDWORKS license?", a: "Yes. Power Surfacing installs on top of an existing SOLIDWORKS installation and requires a valid SOLIDWORKS license. If you need freeform Sub-D modeling without SOLIDWORKS, see Power Surfacing Studio." },
        { q: "What mesh formats can I import?", a: "Power Surfacing imports OBJ and FBX meshes from tools like Modo, 3ds Max, and Maya. For STL files, 3D scans, ZBrush sculpts, and SOLIDWORKS Topology Study meshes, you need Power Surfacing RE." },
        { q: "Is Power Shell included?", a: "Yes — Power Shell and Power Thicken are included with Power Surfacing at no additional cost." },
        { q: "How is Power Surfacing different from Power Surfacing RE?", a: "Power Surfacing RE adds a full reverse-engineering toolset (reference meshes, Quad Wrap, Shrink Wrap, scan repair) on top of everything in Power Surfacing. If you work with scanned or STL meshes, choose RE." },
        { q: "Is there a free trial?", a: "Yes. Download the installer and choose the trial/evaluation option when you launch the product inside SOLIDWORKS." },
      ],
      faqLink: "/resources/faq/solidworks",
    },
  },
  {
    id: "power-surfacing-re-solidworks",
    name: "Power Surfacing RE for SOLIDWORKS",
    shortName: "Power Surfacing RE",
    tagline: "Reverse engineer scanned and polygonal meshes inside SOLIDWORKS",
    description: "Power Surfacing RE gives SOLIDWORKS users a unique set of tools to rebuild shapes from many meshes — 3D scans, FEA meshes, sculpted meshes, 3D printer files, and online model databases — directly inside SOLIDWORKS, without leaving your native CAD environment.",
    image: IMAGES.reSolidworks,
    path: "/products/power-surfacing-re-solidworks",
    testimonialsPath: "/customers/solidworks",
    platform: "SOLIDWORKS Add-in",
    category: "Reverse Engineering",
    inputs: ["3D scans", "STL / OBJ meshes", "Topology Study meshes"],
    outputs: ["SOLIDWORKS solid & surface bodies"],
    pricing: {
      options: [
        { label: "Single Seat License", price: "$3,995", detail: "Perpetual license for one user" },
        { label: "Network License", price: "$4,995", detail: "Floating license shared across your team" },
        { label: "Annual Maintenance", price: "$795", period: "/year", detail: "Updates and support" },
      ],
    },
    testimonials: [
      { quote: "I was able to convert the very complex scan I was working with to a usable surface. It made the workload MUCH easier and I have been able to save at least 40 hours of CAD in this project. Power Surfacing RE has been extremely helpful.", name: "Justin Lefebvre", title: "Derby Building Products Inc." },
      { quote: "Your Power Surfacing RE has been an amazing (and fun) tool to work with. Thanks again for the amazing software — Power Surfacing makes my job fun!", name: "Jesse Maier", title: "Maier Manufacturing, Inc." },
      { quote: "We have some recent successes after the implementation of Power Surfacing which has — in a particular project — phenomenally reduced the time to get parts to tooling, by approximately 4 weeks!", name: "Gavin Colgan-Smith", title: "ARB Corporation Ltd" },
    ],
    features: [
      "Import meshes and display them as a reference mesh",
      "Convert existing SOLIDWORKS geometry into a reference mesh",
      "Automatic Quad Wrap retopology with automatic open-edge closing",
      "Shrink Wrap with automatic self-intersection fixes",
      "Mesh Smooth and Mesh Offset tools",
      "Distance display to measure approximation accuracy",
      "SOLIDWORKS Topology Study to solid geometry conversion",
      "Includes the full Power Surfacing toolset",
    ],
    useCases: [
      "Reverse engineering 3D scanner data directly in SOLIDWORKS",
      "Converting ZBrush sculpted meshes into SOLIDWORKS geometry",
      "Rebuilding parts from FEA and 3D printer mesh files",
      "Recreating or modifying existing SOLIDWORKS parts from meshes",
      "Converting SOLIDWORKS Topology Optimization studies into solids",
    ],
    whoIsItFor: [
      "SOLIDWORKS users who need reverse engineering",
      "Engineers working with 3D scanner data",
      "Teams rebuilding legacy parts with no original CAD data",
      "Manufacturing engineers using Topology Optimization studies",
      "Designers needing to convert sculpted (ZBrush, etc.) meshes into a precise CAD NURBS representation",
    ],
    benefits: [
      "Patent-pending technology captures fine scan detail without bloating model size",
      "Follows curvature and flow lines so creases and ridges aren't washed out",
      "Includes the full Power Surfacing toolset at no extra cost",
      "Automated tools to find and fix scan anomalies like tears and holes",
      "Directly converts SOLIDWORKS Topology Study results into solids",
    ],
    detail: {
      definition: "Power Surfacing RE is a SOLIDWORKS reverse-engineering add-in for engineers and designers that rebuilds editable, native CAD geometry from 3D scans, STL/OBJ meshes, sculpted meshes, FEA meshes, and Topology Study results — without ever leaving SOLIDWORKS.",
      overviewYoutubeId: "sceEZzxyvTg",
      quickFacts: [
        { label: "Runs inside", value: "SOLIDWORKS (64-bit)" },
        { label: "Best for", value: "Reverse engineering scanned and polygonal meshes" },
        { label: "Modeling method", value: "Mesh to Sub-D to CAD/NURBS" },
        { label: "Current release", value: "Tracks Power Surfacing releases — see Release Notes" },
        { label: "Operating system", value: "Windows 10 / 11 (64-bit) with SOLIDWORKS 2021 or newer" },
        { label: "Trial", value: "Free trial — install and choose the evaluation option at launch" },
      ],
      problem: {
        paragraphs: [
          "Do you need to create SOLIDWORKS geometry from scanned meshes, recreate or modify existing parts, or convert meshes from other sources into SOLIDWORKS? Meshes from 3D scanners, FEA tools, sculpting programs, 3D printer files, and online model databases aren't editable CAD — and existing reverse-engineering products specialize in precise prismatic parts, leaving organic and freeform shapes extremely problematic.",
          "Power Surfacing RE solves this with tools that constrain to and reference underlying meshes to capture the original design shape. Its patent-pending technology captures the fine details of a scanned mesh — a level of accuracy that would normally create extremely large models or fail on memory — and uniquely follows the curvature and flow lines of the mesh so creases, ridges, and gullies aren't washed out in the conversion to NURBS. The result is a super-accurate, editable model optimized for the CAD environment, letting you reverse engineer human forms, animal shapes, car bodies, and other freeform representations.",
        ],
      },
      workflowSteps: [
        { title: "Import a reference mesh", description: "Bring in a 3D scan, STL/OBJ mesh, point cloud (OBJ), FEA mesh, or 3D printer file — or convert existing SOLIDWORKS geometry into a reference mesh." },
        { title: "Repair and prepare", description: "Clean up messy imports with Mesh Smooth and Mesh Offset, and use semi-automated tools to find and fix scan anomalies like tears, rips, holes, and overlaps." },
        { title: "Retopologize", description: "Run automatic Quad Wrap retopology — improved for accuracy, speed, and topology, automatically closing most open edges — or draw faces constrained to the reference mesh with automatic face creation." },
        { title: "Capture fine detail", description: "Interpolate or 'vacuum seal' with Shrink Wrap (with automatic self-intersection fixes) to closely approximate the mesh, and verify accuracy with the Distance display." },
        { title: "Convert and keep designing", description: "Convert to native SOLIDWORKS solid or surface bodies, then modify and evolve the design with the full Power Surfacing toolset — included at no extra cost." },
      ],
      capabilities: [
        { name: "Quad Wrap Auto-Retopology", benefit: "Complex meshes converted in minutes, not days.", technical: "Automatically retopologizes the mesh with clean quad flow, following curvature, and automatically detects and closes most open edges." },
        { name: "Shrink Wrap Detail Capture", benefit: "Fine surface detail without model bloat.", technical: "'Vacuum seals' the Sub-D surface to the reference mesh, automatically checking for and fixing self-intersections; patent-pending curvature-driven knot density keeps model size optimal." },
        { name: "Follows Curvature & Flow Lines", benefit: "Creases and ridges survive the conversion.", technical: "Uniquely follows the flow lines and features of the scanned mesh when converting to NURBS, so sharp features aren't washed out." },
        { name: "Anomaly Detection & Repair", benefit: "Restore damaged or incomplete scans.", technical: "Automated tools identify problem areas — tears, rips, holes, overlaps, worn edges — and fix them with minimal effort." },
        { name: "Topology Study Conversion", benefit: "Turn optimization results into real parts.", technical: "Converts SOLIDWORKS Topology Study (topology optimization) mesh output directly into usable SOLIDWORKS solid geometry." },
        { name: "Full Power Surfacing Included", benefit: "Complete Sub-D modeling toolset at no extra cost.", technical: "Every Power Surfacing tool — push-pull editing, sketch creation, Class A conversion, Power Shell, and Power Thicken — is included." },
      ],
      compatibility: {
        requirements: [
          { label: "SOLIDWORKS Version", value: "SOLIDWORKS 2021 or newer (64-bit) for current releases; older SOLIDWORKS versions supported with matching older product versions" },
          { label: "Operating System", value: "Windows 10 or Windows 11, 64-bit" },
          { label: "Processor", value: "3.3 GHz or higher multi-core Intel or AMD (as recommended by SOLIDWORKS)" },
          { label: "Memory (RAM)", value: "16 GB minimum; 32 GB recommended for large scan meshes" },
          { label: "Graphics Card", value: "Certified SOLIDWORKS GPU with OpenGL Shader support and up-to-date drivers" },
        ],
      },
      examples: [
        { title: "ARB Corporation — 4 Weeks Faster to Tooling", description: "After implementing Power Surfacing RE, ARB Corporation phenomenally reduced the time to get parts to tooling on a project by approximately four weeks." },
        { title: "Derby Building Products — 40 Hours Saved", description: "A very complex scan was converted to a usable surface, making the workload much easier and saving at least 40 hours of CAD work on a single project." },
        { title: "Automated Scanned Mesh Conversion", description: "Automated conversion tools greatly simplify the process of turning raw scanned meshes into SOLIDWORKS geometry — with superior accuracy on even large, highly detailed scans." },
        { title: "Topology Optimization to Solids", description: "SOLIDWORKS Topology Study models are converted directly into usable solid geometry, closing the loop between simulation-driven design and manufacturable parts." },
      ],
      industries: ["Industrial Design", "Ergonomics", "Sporting Goods & Clothing", "Toys", "Character Design", "Analysis of Organic Parts", "Dental", "Re-purposing Existing Designs", "Handheld Devices", "Power Tools", "Jewelry", "Cutlery", "Furniture", "Automotive", "Art", "Clay Model Digitizing", "Cosmetics"],
      faq: [
        { q: "Do I need a SOLIDWORKS license?", a: "Yes. Power Surfacing RE installs on top of an existing SOLIDWORKS installation and requires a valid SOLIDWORKS license. For reverse engineering without SOLIDWORKS, see Power Surfacing RE Studio." },
        { q: "What meshes can I reverse engineer?", a: "3D scanner output, STL and OBJ meshes, point clouds (OBJ), FEA meshes, 3D printer files, ZBrush and other sculpted meshes, online model database downloads, and SOLIDWORKS Topology Study results. You can also convert existing SOLIDWORKS geometry into a reference mesh." },
        { q: "How is it different from Power Surfacing?", a: "Power Surfacing RE includes the complete Power Surfacing toolset and adds the reverse-engineering tools: reference meshes, Quad Wrap, Shrink Wrap, mesh repair, Distance display, and Topology Study conversion." },
        { q: "How accurate are the converted surfaces?", a: "Patent-pending technology follows the curvature and flow lines of the mesh and uses curvature-driven surface knot density, capturing fine detail to your desired accuracy without bloating the model. The Distance display lets you measure the approximation against the reference mesh." },
        { q: "Is there a free trial?", a: "Yes. Download the installer and choose the trial/evaluation option when you launch the product inside SOLIDWORKS." },
      ],
      faqLink: "/resources/faq/solidworks",
    },
  },
  {
    id: "power-shell-solidworks",
    name: "Power Shell for SOLIDWORKS",
    shortName: "Power Shell",
    tagline: "When Shell fails, Power Shell prevails",
    description: "Power Shell (which includes Power Thicken) solves a long-standing CAD problem — shelling and thickening complex, difficult, or organic surfaces and solids that standard SOLIDWORKS Shell and Thicken commands cannot handle.",
    image: IMAGES.powerShell,
    path: "/products/power-shell-solidworks",
    testimonialsPath: "/customers/solidworks",
    platform: "SOLIDWORKS Add-in",
    category: "Shelling",
    inputs: ["SOLIDWORKS solids & surfaces"],
    outputs: ["Shelled / thickened SOLIDWORKS bodies"],
    pricing: {
      options: [
        { label: "Single Seat License", price: "$1,495", detail: "Perpetual license for one user" },
      ],
      note: "Included free with Power Surfacing and Power Surfacing RE.",
    },
    testimonials: [
      { quote: "Power Shell really has been amazing. Truly a massive help in frustration and time. SOLIDWORKS shell always fails, and the workarounds are very tedious and time consuming. It's the only 3rd-party tool I've purchased for SOLIDWORKS.", name: "Sean Conner", title: "Hickenbottom, Inc." },
      { quote: "Power Shell. Wow! What a tool. I have been working on a golf club driver head — very organic shapes, sharp features with small break rads. SW on its own would never manage this operation. I'm impressed. Well done and thank you.", name: "Dean Bourne", title: "3D Design Limited" },
      { quote: "Has thrown up many new possibilities and re-design that I could not have done before. Has revolutionised my business in a similar way that Power Surfacing did a few years back. Will save a lot of money and time.", name: "Stuart Brown", title: "3D Engineers" },
    ],
    features: [
      "Shell, Hollow, and Thicken commands",
      "Works with solids (Power Shell) or surfaces (Power Thicken)",
      "Offset inside or outside with clearance values",
      "Handles small radii, large radii, and intersected surfaces",
      "Verification of offset distances (thickness)",
      "Rounding of corners and edges",
      "Undo/Redo with live preview",
      "Full integration with the SOLIDWORKS Feature Tree",
    ],
    useCases: [
      "Shelling organic, complex, or self-intersecting geometry",
      "Thickening surface bodies that fail with native Thicken",
      "Preparing consumer products for injection molding",
      "Creating uniform or variable wall thickness on any geometry",
      "Succeeding on models where SOLIDWORKS Shell produces errors",
    ],
    whoIsItFor: [
      "SOLIDWORKS users with complex shelling needs",
      "Manufacturing engineers preparing parts for injection molding",
      "Product designers working with organic geometry",
      "Engineers working with imported or scanned geometry",
    ],
    benefits: [
      "Solves shelling and thickening failures common to virtually all CAD systems",
      "Patent-pending technology built for complex offsetting cases",
      "Included free with Power Surfacing and Power Surfacing RE",
      "Proven in side-by-side tests where native SOLIDWORKS Shell fails at greater thicknesses",
      "Full feature tree integration with undo/redo and live preview",
    ],
    detail: {
      definition: "Power Shell (which includes Power Thicken) is a SOLIDWORKS add-in for engineers whose Shell and Thicken commands fail — it hollows and thickens complex, organic, or self-intersecting solids and surfaces directly inside SOLIDWORKS using patent-pending offsetting technology.",
      overviewYoutubeId: "2s9nVQPv0Ak",
      quickFacts: [
        { label: "Runs inside", value: "SOLIDWORKS (64-bit)" },
        { label: "Best for", value: "Shelling & thickening geometry that native commands can't handle" },
        { label: "Method", value: "Patent-pending offsetting technology" },
        { label: "Current release", value: "See Release Notes for the latest version" },
        { label: "Operating system", value: "Windows 10 / 11 (64-bit) with SOLIDWORKS 2021 or newer" },
        { label: "Trial", value: "Free trial — install and choose the evaluation option at launch" },
      ],
      problem: {
        paragraphs: [
          "Do you ever run into problems trying to Shell or Thicken your parts? Are you tired of tweaking your models and making endless adjustments just to make the Shell and Thicken commands work? Shelling and thickening failures are a common issue for virtually all CAD systems — especially on complex, organic, or self-intersecting geometry.",
          "Power Shell introduces new patent-pending technology that finally addresses this long-standing issue. Power Shell and Power Thicken complement the native SOLIDWORKS tools: when Shell and Thicken fail, use Power Shell to get the job done instead of wasting time modifying your design so the native command might work. When Shell fails, Power Shell prevails.",
        ],
      },
      workflowSteps: [
        { title: "Select the body", description: "Pick a solid body (Power Shell) or a surface body (Power Thicken) — including complex, organic, or imported geometry that native commands reject." },
        { title: "Set thickness and direction", description: "Choose the wall thickness, offset inside or outside, and optional clearance values. Round corners and edges as needed." },
        { title: "Preview and verify", description: "See a live preview of the result and verify offset distances (thickness) before committing — with full undo/redo." },
        { title: "Apply as a feature", description: "The result integrates with the SOLIDWORKS Feature Tree like any other feature, ready for downstream operations." },
      ],
      capabilities: [
        { name: "Succeeds Where Shell Fails", benefit: "No more redesigning parts just to make Shell work.", technical: "Handles complex surfaces, small radii, large radii, intersected surfaces, and virtually all difficult cases for standard shelling commands." },
        { name: "Solids and Surfaces", benefit: "One toolset for both body types.", technical: "Power Shell works on solid bodies; Power Thicken works on surface bodies. Both offset inside or outside with clearance value support." },
        { name: "Shell, Hollow & Thicken", benefit: "Complete wall-creation toolkit.", technical: "Shell removes faces and hollows with uniform walls; Hollow creates fully enclosed cavities; Thicken turns surfaces into solids." },
        { name: "Thickness Verification", benefit: "Confidence the walls are what you specified.", technical: "Built-in verification of offset distances confirms actual wall thickness across the entire part." },
        { name: "Corner & Edge Rounding", benefit: "Clean results on sharp geometry.", technical: "Automatic rounding of corners and edges during the offset operation where sharp features would otherwise fail." },
        { name: "Feature Tree Integration", benefit: "Behaves like a native SOLIDWORKS command.", technical: "Full integration with SOLIDWORKS Feature Tree editing, plus live preview and undo/redo." },
      ],
      compatibility: {
        requirements: [
          { label: "SOLIDWORKS Version", value: "SOLIDWORKS 2021 or newer (64-bit) for current releases; older SOLIDWORKS versions supported with matching older product versions" },
          { label: "Operating System", value: "Windows 10 or Windows 11, 64-bit" },
          { label: "Processor", value: "3.3 GHz or higher multi-core Intel or AMD (as recommended by SOLIDWORKS)" },
          { label: "Memory (RAM)", value: "16 GB minimum" },
          { label: "Graphics Card", value: "Certified SOLIDWORKS GPU with OpenGL Shader support and up-to-date drivers" },
        ],
      },
      benchmark: {
        title: "Side-by-Side: SOLIDWORKS Shell vs. Power Shell",
        subtitle: "Real models tested at wall thicknesses from 0.1 to 10. Native SOLIDWORKS Shell fails as thickness grows or geometry gets organic — Power Shell succeeds at every thickness on every model.",
        rows: [
          { model: "Mixer", sw: "Succeeds up to 0.5 — fails at 1 and above", swSucceeds: true, ps: "Succeeds at all thicknesses (0.1–10)" },
          { model: "Dog figure (organic)", sw: "Fails at all thicknesses", swSucceeds: false, ps: "Succeeds at all thicknesses (0.1–10)" },
          { model: "Gas tank", sw: "Succeeds up to 0.5 — fails at 1 and above", swSucceeds: true, ps: "Succeeds at all thicknesses (0.1–10)" },
          { model: "Sports drink bottle", sw: "Fails at all thicknesses", swSucceeds: false, ps: "Succeeds at all thicknesses (0.1–10)" },
          { model: "Circular saw handle", sw: "Succeeds up to 1 — fails at 2 and above", swSucceeds: true, ps: "Succeeds at all thicknesses (0.1–10)" },
          { model: "Bruce Lee figure (organic)", sw: "Fails at all thicknesses", swSucceeds: false, ps: "Succeeds at all thicknesses (0.1–10)" },
          { model: "Soap bottle", sw: "Succeeds up to 0.5 — fails at 1 and above", swSucceeds: true, ps: "Succeeds at all thicknesses (0.1–10)" },
          { model: "Tall bottle", sw: "Succeeds up to 0.5 — fails at 1 and above", swSucceeds: true, ps: "Succeeds at all thicknesses (0.1–10)" },
          { model: "Bulldog figure (organic)", sw: "Fails at all thicknesses", swSucceeds: false, ps: "Succeeds at all thicknesses (0.1–10)" },
        ],
      },
      faq: [
        { q: "Do I need a SOLIDWORKS license?", a: "Yes. Power Shell installs on top of an existing SOLIDWORKS installation and requires a valid SOLIDWORKS license." },
        { q: "Is Power Shell included with other products?", a: "Yes — Power Shell and Power Thicken are included free with both Power Surfacing and Power Surfacing RE. Buy Power Shell standalone only if you don't need the surfacing products." },
        { q: "What's the difference between Power Shell and Power Thicken?", a: "Power Shell works on solid bodies (hollowing them with a wall thickness); Power Thicken works on surface bodies (turning them into solids). Both are included in the same product." },
        { q: "Should I replace the native Shell command?", a: "No — Power Shell complements the native tools. Use SOLIDWORKS Shell/Thicken when they work; when they fail, use Power Shell instead of redesigning your part." },
        { q: "Is there a free trial?", a: "Yes. Download the installer and choose the trial/evaluation option when you launch the product inside SOLIDWORKS." },
      ],
      faqLink: "/resources/faq/solidworks",
    },
  },
];

export const WORKFLOWS = [
  { id: "reverse-engineering", name: "Reverse Engineering Mechanical Parts", path: "/workflows/reverse-engineering", image: "/assets/wf-reverse-engineering.jpg", description: "Convert physical objects and 3D scans into editable CAD geometry using advanced reverse engineering workflows.", startingData: "A physical part or a 3D scan mesh", result: "An editable, manufacturable CAD solid", recommendedProduct: "Power Surfacing RE Studio" },
  { id: "scan-to-cad", name: "Scan-to-CAD", path: "/workflows/scan-to-cad", image: "/assets/wf-scan-to-cad.jpg", description: "Transform raw 3D scan data from any scanner into clean, manufacturing-ready CAD surfaces and solids.", startingData: "Raw 3D scanner data (STL, OBJ, point cloud)", result: "Clean NURBS surfaces and solids", recommendedProduct: "Power Surfacing RE Studio" },
  { id: "mesh-to-cad", name: "Mesh-to-CAD", path: "/workflows/mesh-to-cad", image: "/assets/wf-mesh-to-cad.jpg", description: "Convert triangulated mesh data into smooth NURBS surfaces and solid CAD models.", startingData: "A triangulated mesh (STL or OBJ)", result: "A smooth NURBS CAD model", recommendedProduct: "Power Surfacing RE Studio" },
  { id: "sculpted-mesh-to-cad", name: "ZBrush / Sculpted Mesh to CAD", path: "/workflows/sculpted-mesh-to-cad", image: "/assets/wf-zbrush.jpg", description: "Convert ZBrush, Mudbox, and other sculpted mesh models into production-ready NURBS CAD surfaces.", startingData: "A ZBrush or other sculpted mesh", result: "Production-ready NURBS CAD surfaces", recommendedProduct: "Power Surfacing RE for SOLIDWORKS" },
  { id: "freeform-sub-d", name: "Freeform Sub-D Design", path: "/workflows/freeform-sub-d", image: "/assets/wf-freeform.jpg", description: "Use subdivision surface modeling to create smooth, organic freeform shapes with intuitive control.", startingData: "A freeform or organic design idea", result: "Smooth Class A Sub-D surfaces as NURBS", recommendedProduct: "Power Surfacing Studio" },
  { id: "industrial-design-solidworks", name: "Industrial Design in SOLIDWORKS", path: "/workflows/industrial-design-solidworks", image: "/assets/wf-industrial.jpg", description: "Create beautiful, ergonomic industrial designs directly inside SOLIDWORKS using Sub-D surfacing.", startingData: "A SOLIDWORKS part or assembly", result: "Organic Class A surfaces in your feature tree", recommendedProduct: "Power Surfacing for SOLIDWORKS" },
  { id: "shelling-thickening", name: "Shelling and Thickening", path: "/workflows/shelling-thickening", image: "/assets/wf-shelling.jpg", description: "Shell and thicken complex geometry that standard CAD tools cannot handle.", startingData: "A complex solid or surface body", result: "A shelled or thickened part with clean walls", recommendedProduct: "Power Shell for SOLIDWORKS (also included in all Power Surfacing products)" },
];

export const CAPABILITIES = [
  { name: "Dimension-Driven Sketching", icon: "Ruler", description: "Precisely control geometry with parametric dimensions, constraints, and relationships." },
  { name: "Feature-Based Modeling", icon: "Layers", description: "Build complex models with a construction history that can be edited and rolled back at any time." },
  { name: "Surfacing & Solids", icon: "Box", description: "Combine surface modeling and solid modeling for complete product design workflows." },
  { name: "Freeform Sub-D Design", icon: "Spline", description: "Create smooth, organic shapes using subdivision surface modeling with intuitive control." },
  { name: "Reverse Engineering", icon: "ScanLine", description: "Convert 3D scans, meshes, and point clouds into editable CAD geometry." },
  { name: "Scan/Mesh-to-CAD", icon: "FileInput", description: "Import and convert STL, OBJ, and mesh files into NURBS surfaces and solid models." },
  { name: "SOLIDWORKS Workflows", icon: "Workflow", description: "Extend SOLIDWORKS with freeform surfacing, reverse engineering, and advanced shelling." },
  { name: "Shelling & Thickening", icon: "Shell", description: "Handle complex shelling and thickening operations that standard tools cannot solve." },
];

export const NAV_ITEMS = [
  {
    label: "Products",
    path: "/products",
    children: [
      { label: "All Products", path: "/products" },
      { label: "Power Surfacing RE Studio", path: "/products/power-surfacing-re-studio" },
      { label: "Power Surfacing Studio", path: "/products/power-surfacing-studio" },
      { label: "Power Surfacing for SOLIDWORKS", path: "/products/power-surfacing-solidworks" },
      { label: "Power Surfacing RE for SOLIDWORKS", path: "/products/power-surfacing-re-solidworks" },
      { label: "Power Shell for SOLIDWORKS", path: "/products/power-shell-solidworks" },
      { label: "Compare Products", path: "/products/comparison" },
    ],
  },
  {
    label: "Workflows",
    path: "/workflows",
    children: [
      { label: "All Workflows", path: "/workflows" },
      { label: "Reverse Engineering Mechanical Parts", path: "/workflows/reverse-engineering" },
      { label: "Scan-to-CAD", path: "/workflows/scan-to-cad" },
      { label: "Mesh-to-CAD", path: "/workflows/mesh-to-cad" },
      { label: "ZBrush / Sculpted Mesh to CAD", path: "/workflows/sculpted-mesh-to-cad" },
      { label: "Freeform Sub-D Design", path: "/workflows/freeform-sub-d" },
      { label: "Industrial Design in SOLIDWORKS", path: "/workflows/industrial-design-solidworks" },
      { label: "Shelling and Thickening", path: "/workflows/shelling-thickening" },
    ],
  },
  {
    label: "Learn",
    path: "/resources",
    children: [
      { label: "Learning Center", path: "/resources" },
      { label: "How It Works", path: "/technology" },
      { label: "Video Library", path: "/resources/videos" },
      { label: "Product Demos", path: "/resources/demos" },
      { label: "Tutorials", path: "/resources/tutorials" },
      { label: "FAQ", path: "/resources/faq" },
      { label: "Events & Webinars", path: "/events" },
    ],
  },
  {
    label: "Pricing & Licensing",
    path: "/pricing",
    children: [
      { label: "Pricing & Licensing", path: "/pricing" },
      { label: "Pricing", path: "/pricing/plans" },
      { label: "Free Trial", path: "/pricing/downloads" },
      { label: "Upgrades & Maintenance", path: "/pricing/upgrades" },
      { label: "Authorized Resellers", path: "/resellers" },
    ],
  },
  {
    label: "Support",
    path: "/support",
    children: [
      { label: "Support Home", path: "/support" },
      { label: "Getting Started", path: "/support/getting-started" },
      { label: "Tutorials by Product", path: "/support/tutorials" },
      { label: "Install & Activate", path: "/support/installation" },
      { label: "System Requirements", path: "/support/system-requirements" },
      { label: "Release Notes", path: "/support/release-notes" },
      { label: "Downloads", path: "/pricing/downloads" },
      { label: "Contact Support", path: "/support/contact" },
    ],
  },
];

function ytThumb(id) {
  return `https://img.youtube.com/vi/${id}/hqdefault.jpg`;
}

export const SAMPLE_VIDEOS = [
  { id: "v1", youtubeId: "yZr-buzOCGc", title: "Solids# MeshToCAD Basic Usage", product: "Power Surfacing RE Studio", type: "Demo", workflow: "Mesh-to-CAD", level: "Beginner", duration: "9:40", thumbnail: ytThumb("yZr-buzOCGc") },
  { id: "v2", youtubeId: "F9U8-l1y3Kw", title: "Solids# MeshToCAD Recorded Webinar", product: "Power Surfacing RE Studio", type: "Overview", workflow: "Reverse Engineering Mechanical Parts", level: "Beginner", duration: "34:20", thumbnail: ytThumb("F9U8-l1y3Kw") },
  { id: "v3", youtubeId: "tVl9xQwSiCE", title: "Power Surfacing Technology Overview", product: "Power Surfacing Studio", type: "Overview", workflow: "Freeform Sub-D Design", level: "Beginner", duration: "5:22", thumbnail: ytThumb("tVl9xQwSiCE") },
  { id: "v4", youtubeId: "WI17SjGiXaE", title: "Gas Can Modeling Tutorial", product: "Power Surfacing Studio", type: "Tutorial", workflow: "Feature-Based Modeling", level: "Beginner", duration: "18:05", thumbnail: ytThumb("WI17SjGiXaE") },
  { id: "v5", youtubeId: "ombvLO6vu9c", title: "Signet Ring Build", product: "Power Surfacing Studio", type: "Tutorial", workflow: "Freeform Sub-D Design", level: "Intermediate", duration: "12:50", thumbnail: ytThumb("ombvLO6vu9c") },
  { id: "v6", youtubeId: "k-Bxe4Al_VQ", title: "Getting Started with Power Surfacing", product: "Power Surfacing for SOLIDWORKS", type: "Tutorial", workflow: "Industrial Design in SOLIDWORKS", level: "Beginner", duration: "14:15", thumbnail: ytThumb("k-Bxe4Al_VQ") },
  { id: "v7", youtubeId: "Fjg35m5MTMI", title: "Understanding the Gizmo", product: "Power Surfacing for SOLIDWORKS", type: "Tutorial", workflow: "Freeform Sub-D Design", level: "Beginner", duration: "7:30", thumbnail: ytThumb("Fjg35m5MTMI") },
  { id: "v8", youtubeId: "rP7KfmP0Mkg", title: "Creating a Custom Ring in SOLIDWORKS", product: "Power Surfacing for SOLIDWORKS", type: "Tutorial", workflow: "Industrial Design in SOLIDWORKS", level: "Intermediate", duration: "16:45", thumbnail: ytThumb("rP7KfmP0Mkg") },
  { id: "v9", youtubeId: "pvLbDM9f58A", title: "Embossed Brick Pattern Tutorial", product: "Power Surfacing for SOLIDWORKS", type: "Tutorial", workflow: "Freeform Sub-D Design", level: "Intermediate", duration: "9:10", thumbnail: ytThumb("pvLbDM9f58A") },
  { id: "v10", youtubeId: "l87K8yfbEdY", title: "Power Surfacing 10.0 New Features", product: "Power Surfacing for SOLIDWORKS", type: "Overview", workflow: "Feature-Based Modeling", level: "Intermediate", duration: "11:20", thumbnail: ytThumb("l87K8yfbEdY") },
  { id: "v11", youtubeId: "sceEZzxyvTg", title: "Power Surfacing RE 5.0 Overview", product: "Power Surfacing RE for SOLIDWORKS", type: "Overview", workflow: "Reverse Engineering", level: "Beginner", duration: "13:40", thumbnail: "https://img.youtube.com/vi/sceEZzxyvTg/default.jpg" },
  { id: "v12", youtubeId: "4LjOmm-u8XI", title: "Reverse Engineering Scanned Meshes in SOLIDWORKS", product: "Power Surfacing RE for SOLIDWORKS", type: "Demo", workflow: "Scan-to-CAD", level: "Intermediate", duration: "28:15", thumbnail: ytThumb("4LjOmm-u8XI") },
  { id: "v13", youtubeId: "SIX_m3N37e4", title: "Converting ZBrush Meshes to SOLIDWORKS (ZBrush Remesher)", product: "Power Surfacing RE for SOLIDWORKS", type: "Tutorial", workflow: "ZBrush / Sculpted Mesh to CAD", level: "Intermediate", duration: "10:35", thumbnail: ytThumb("SIX_m3N37e4") },
  { id: "v14", youtubeId: "dtXuwIIwNcY", title: "Working with Topology Study Meshes", product: "Power Surfacing RE for SOLIDWORKS", type: "Demo", workflow: "Topology Optimization to CAD", level: "Advanced", duration: "12:05", thumbnail: ytThumb("dtXuwIIwNcY") },
  { id: "v15", youtubeId: "Cd439HkG9ow", title: "Quad Wrap Options Explained", product: "Power Surfacing RE for SOLIDWORKS", type: "Tutorial", workflow: "Mesh-to-CAD", level: "Intermediate", duration: "8:50", thumbnail: ytThumb("Cd439HkG9ow") },
  { id: "v16", youtubeId: "bUTIEH12be4", title: "Reverse Engineering Real World Scans", product: "Power Surfacing RE for SOLIDWORKS", type: "Demo", workflow: "Scan-to-CAD", level: "Advanced", duration: "15:30", thumbnail: ytThumb("bUTIEH12be4") },
  { id: "v17", youtubeId: "2s9nVQPv0Ak", title: "Power Shell Introduction", product: "Power Shell for SOLIDWORKS", type: "Overview", workflow: "Shelling and Thickening", level: "Beginner", duration: "6:15", thumbnail: ytThumb("2s9nVQPv0Ak") },
  { id: "v18", youtubeId: "IeAlGJJtXps", title: "Power Shell Presentation", product: "Power Shell for SOLIDWORKS", type: "Demo", workflow: "Shelling and Thickening", level: "Beginner", duration: "9:00", thumbnail: ytThumb("IeAlGJJtXps") },
];