// Centralized site data for nPower Software / Power Surfacing

export const IMAGES = {
  hero: "/assets/hero.png",
  reStudio: "/assets/product-re-studio.webp",
  studio: "/assets/product-studio.webp",
  visualize: "/assets/product-studio.webp",
  solidworks: "/assets/product-solidworks.webp",
  reSolidworks: "/assets/product-re-solidworks.webp",
  powerShell: "/assets/product-power-shell.webp",
  cyborg3d: "/assets/img-cyborg3d.png",
  scanToCad: "/assets/img-scan-to-cad.png",
  freeform: "/assets/img-freeform.png",
  topology: "/assets/img-topology.png",
  industrial: "/assets/img-industrial.png",
};

export const PRODUCTS = [
  {
    id: "power-surfacing-re-studio",
    name: "Power Surfacing RE Studio",
    pageTitle: "Power Surfacing RE Studio | Scan-to-CAD Reverse Engineering",
    pageDescription: "Convert 3D scan meshes, sculpted meshes, stl meshes and CAD meshes into editable CAD surfaces and solids using reverse engineering, dimension-driven sketching, feature modeling and Sub-D tools.",
    shortName: "RE Studio",
    tagline: "Standalone reverse-engineering software for scanned and sculpted meshes",
    description: "The most advanced standalone reverse-engineering software for scanned meshes, ZBrush sculpts, and polygonal geometry. Power Surfacing RE Studio captures very fine surface detail with a highly automated workflow, converting complex meshes into high-quality NURBS surfaces in a matter of minutes. It includes the complete Power Surfacing Studio toolset, adding reverse-engineering capabilities on top of full hybrid Sub-D / NURBS modeling. It also includes the full functionality of Power Surfacing Visualize plus the KeyShot render engine.",
    image: IMAGES.reStudio,
    path: "/products/power-surfacing-re-studio",
    testimonialsPath: "/customers/power-surfacing-re-studio",
    platform: "Standalone",
    category: "Reverse Engineering",
    inputs: ["STL", "OBJ meshes", "Sculpted meshes"],
    outputs: ["STEP", "STL", "Wavefront OBJ", "Native SOLIDWORKS features"],
    pricing: {
      options: [
        { label: "Perpetual License", price: "$6,995", originalPrice: "$8,995", badge: "Intro pricing through June 2027", detail: "One-time purchase, yours forever" },
        { label: "Annual Maintenance", price: "$1,795", period: "/year", detail: "Updates and support for perpetual licenses" },
        { label: "Annual Subscription", price: "$2,995", originalPrice: "$3,995", period: "/first year", badge: "First-year intro price", detail: "$3,995/year thereafter — includes updates and support" },
      ],
      note: "Introductory perpetual pricing available through June 2027. Choose a perpetual license with optional maintenance, or a lower-upfront annual subscription.",
    },
    testimonials: [
      { quote: "RE Studio converted a scan that took us days in other tools into clean NURBS surfaces in under an hour. The Quad Wrap retopology is remarkable.", name: "David M.", title: "Reverse Engineering Specialist, Aerospace Supplier" },
      { quote: "We digitize clay models for consumer products, and the fine detail capture is the best we've seen at any price point.", name: "Sarah K.", title: "Design Director, Product Studio" },
      { quote: "The STEP export drops straight into our downstream CAD with no cleanup. It just works.", name: "James T.", title: "Mechanical Engineer, Medical Devices" },
    ],
    features: [
      "Includes everything in Power Surfacing Studio — full Sub-D and NURBS modeling",
      "Includes the full functionality of Power Surfacing Visualize plus the KeyShot render engine",
      "Import of STL and Wavefront OBJ files",
      "Quad Wrap retopology that follows curvature flow",
      "Identification and extraction of mechanical surfaces and solids (planes, cylinders, cones, spheres, extruded, revolved)",
      "Shrink Wrap tool adds fine detail without adding polygons",
      "Mesh repair, smoothing, and hole-filling tools",
      "Sub-D to Brep NURBS conversion with G2 edge continuity",
      "Advanced shelling and variable wall thickness",
      "Export to STEP, STL, and Wavefront OBJ, plus native SOLIDWORKS feature transfer",
      "SOLIDWORKS Topology Study mesh conversion",
    ],
    useCases: [
      "Reverse engineering scanned meshes into accurate, editable NURBS geometry",
      "Converting ZBrush and other sculpted meshes into CAD-ready surfaces",
      "Rebuilding human forms, animal shapes, and other organic geometry",
      "Capturing fine surface detail on jewelry, cutlery, and consumer products",
      "Digitizing clay models and physical prototypes for CAD",
      "Converting SOLIDWORKS Topology Study output into usable solid geometry",
    ],
    whoIsItFor: [
      "Reverse engineers and 3D scan technicians",
      "Industrial and product designers working with organic shapes",
      "Medical, dental, and prosthetics professionals working from scans",
      "Artists digitizing sculptures and fine art pieces",
      "Toy, character, and game controller designers",
      "Jewelry, cutlery, and consumer goods designers",
      "Engineers digitizing clay models and physical prototypes",
    ],
    benefits: [
      "Aggressively priced compared to other reverse-engineering solutions",
      "Captures very fine detail on scanned and sculpted meshes",
      "Highly automated workflow processes complex meshes in minutes",
      "Includes Visualize CAD import, cleanup, and KeyShot rendering — no extra KeyShot license",
      "Produces high-quality, G2-continuous NURBS surfaces",
      "Exports to STEP, STL, and Wavefront OBJ — plus native SOLIDWORKS feature transfer",
    ],
  },
  {
    id: "power-surfacing-studio",
    name: "Power Surfacing Studio",
    pageTitle: "Power Surfacing Studio | Sub-D & NURBS CAD Design",
    pageDescription: "Standalone hybrid Sub-D / NURBS modeling software for Class A surfacing, dimension-driven sketching, and feature-based design.",
    shortName: "Studio",
    tagline: "Standalone freeform Sub-D and Class A surfacing design software",
    description: "Model complex, aesthetically pleasing Class A surfaces with the ease of digital clay. Power Surfacing Studio delivers hybrid Sub-D / NURBS modeling — push, pull, and sculpt freeform shapes, then refine them with dimension-driven, feature-based control — no third-party CAD license required. It includes the full functionality of Power Surfacing Visualize plus the KeyShot render engine.",
    image: IMAGES.studio,
    path: "/products/power-surfacing-studio",
    testimonialsPath: "/customers/power-surfacing-studio",
    platform: "Standalone",
    category: "CAD Design",
    inputs: ["Sketches", "OBJ / FBX meshes", "Primitive shapes"],
    outputs: ["Class A NURBS surfaces", "Solid bodies", "STEP"],
    pricing: {
      options: [
        { label: "Perpetual License", price: "$1,995", originalPrice: "$3,495", badge: "Intro pricing through June 2027", detail: "One-time purchase, yours forever" },
        { label: "Annual Maintenance", price: "$695", period: "/year", detail: "Updates and support for perpetual licenses" },
        { label: "Annual Subscription", price: "$995", originalPrice: "$1,395", period: "/first year", badge: "First-year intro price", detail: "$1,395/year thereafter — includes updates and support" },
      ],
      note: "Introductory pricing available through June 2027. Choose a perpetual license with optional maintenance, or a lower-upfront annual subscription.",
    },
    testimonials: [
      { quote: "Studio gives me true Class A surfaces with the freedom of digital clay. I moved my entire concept workflow into it.", name: "Elena R.", title: "Industrial Designer, Consumer Electronics" },
      { quote: "The mix of dimension-driven sketching and Sub-D freeform modeling is something no other standalone tool offers at this price.", name: "Marcus B.", title: "Freelance Product Designer" },
      { quote: "We prototype bottle and handle designs in hours instead of days. Clients notice the surface quality immediately.", name: "Priya S.", title: "Principal, Design Consultancy" },
    ],
    features: [
      "Includes the full functionality of Power Surfacing Visualize plus the KeyShot render engine",
      "Primitive shapes: box, cylinder, torus, and more",
      "Dynamic push-pull editing with constrained editing and soft selection",
      "Core tools: Extrude, Inset, Insert Loops, Bridge",
      "Mirror, Bend, Edge Weighting, and Subdivide",
      "Advanced tools: Extend, Edge Extrude, Insert Edge, Shell, Thicken",
      "Import of OBJ and FBX meshes from Modo, 3ds Max, and Maya",
      "Conversion to Class A NURBS surface or solid bodies",
      "Dimension-driven, feature-based construction history",
    ],
    useCases: [
      "Designing complex freeform, organic industrial design shapes",
      "Modeling consumer products like bottles, handles, and enclosures",
      "Creating jewelry, cutlery, and character designs with Sub-D precision",
      "Combining dimension-driven sketches with freeform Sub-D surfaces",
      "Building Class A automotive and sporting goods surfaces",
      "Prototyping product concepts before committing to CAD detail",
    ],
    whoIsItFor: [
      "Industrial designers",
      "Product designers",
      "Toy, character, and consumer goods designers",
      "Freelance CAD professionals",
      "Design studios and consultancies",
    ],
    benefits: [
      "Unifies Sub-D freeform modeling and NURBS precision in one application",
      "Manipulating parts is as simple as modeling with clay",
      "Dimension-driven Sub-D modeling for repeatable, precise design",
      "No third-party CAD license required",
      "Includes Visualize CAD import, cleanup, and KeyShot rendering — no extra KeyShot license",
      "Full feature-based construction history for easy revisions",
    ],
  },
  {
    id: "power-surfacing-visualize",
    name: "Power Surfacing Visualize",
    pageTitle: "Power Surfacing Visualize | CAD Visualization & KeyShot Rendering",
    pageDescription: "Standalone CAD visualization and rendering-prep software with KeyShot bundled. Import engineering models, clean up assemblies, and create product visuals — no extra KeyShot license and no full CAD seat required.",
    shortName: "Visualize",
    tagline: "CAD import, cleanup, tessellation, bundled KeyShot, and mesh export for Blender, Modo, 3ds Max, and Maya.",
    description: "A standalone CAD visualization and rendering-prep system with KeyShot bundled. Import engineering models, clean up assemblies, control tessellation and materials, and create product visuals without needing a full CAD seat — and without buying a separate KeyShot license. Prepare and export meshes for other visualization packages such as Blender, Modo, 3ds Max, and Maya.",
    image: IMAGES.visualize,
    path: "/products/power-surfacing-visualize",
    platform: "Standalone",
    category: "CAD Visualization",
    inputs: ["STEP", "IGES", "SAT", "Rhino", "OBJ", "STL", "3MF", "SOLIDWORKS files"],
    outputs: ["KeyShot", "OBJ", "STL", "glTF"],
    pricing: {
      options: [
        { label: "Perpetual License", price: "$995", originalPrice: "$1,495", badge: "Intro pricing through June 2027", detail: "One-time purchase, yours forever" },
        { label: "Annual Maintenance", price: "$295", period: "/year", detail: "Updates and support for perpetual licenses" },
        { label: "Annual Subscription", price: "$795", period: "/year", detail: "Includes updates and support" },
      ],
      note: "Introductory perpetual pricing available through June 2027. KeyShot is bundled — no extra KeyShot license purchase is required. Power Surfacing Visualize is a visualization and translation product — not a replacement for Power Surfacing Studio or RE Studio.",
    },
    testimonials: [],
    features: [
      "Import STEP, IGES, SAT, Rhino, OBJ, STL, 3MF, and other common CAD and mesh formats",
      "Open SOLIDWORKS files or receive direct export from SOLIDWORKS, depending on licensing",
      "Assembly browser with part and material organization",
      "Tessellation controls for visualization-quality meshes",
      "Face and part visibility tools",
      "Material assignment and color cleanup",
      "Exploded-view and simple positioning tools",
      "KeyShot is bundled — render product visuals with no extra KeyShot license purchase",
      "Prepare and export meshes for Blender, Modo, 3ds Max, Maya, and other visualization packages",
      "Export to KeyShot, OBJ, STL, and glTF",
    ],
    useCases: [
      "Preparing engineering CAD models for product visualization and rendering",
      "Importing STEP, IGES, SAT, Rhino, and SOLIDWORKS data for cleanup and tessellation",
      "Assigning materials and cleaning color on assemblies before rendering",
      "Creating exploded views and simple part positioning for product visuals",
      "Producing KeyShot renderings with the bundled KeyShot — no extra KeyShot license and no full CAD seat",
      "Preparing and exporting meshes for Blender, Modo, 3ds Max, Maya, and other visualization packages",
      "Translating CAD data into OBJ, STL, or glTF for downstream visualization",
    ],
    whoIsItFor: [
      "Visualization and rendering specialists working from engineering CAD",
      "Marketing and product-launch teams that need CAD-based visuals",
      "Designers who need CAD import and cleanup without a full modeling seat",
      "Teams replacing a translator/visualization utility rather than a CAD modeler",
      "Users who prepare meshes for Blender, Modo, 3ds Max, Maya, or other visualization packages",
      "Users who want bundled KeyShot rendering without a separate KeyShot license",
    ],
    benefits: [
      "CAD visualization, translation, and rendering prep",
      "Create product visuals without needing a full CAD seat",
      "KeyShot is bundled — no extra KeyShot license purchase is required",
      "Prepare and export meshes for Blender, Modo, 3ds Max, and Maya",
      "Cleans up assemblies, tessellation, and materials before rendering",
      "Natural first step before Power Surfacing Studio or RE Studio",
    ],
  },
  {
    id: "power-surfacing-solidworks",
    name: "Power Surfacing for SOLIDWORKS",
    pageTitle: "Power Surfacing for SOLIDWORKS | Sub-D Add-In",
    pageDescription: "Freeform Sub-D surfacing add-in for SOLIDWORKS. Model Class A surfaces like digital clay and convert them into SOLIDWORKS features that contain either solid and/or surface bodies.",
    shortName: "Power Surfacing",
    tagline: "Freeform Sub-D and Class A surfacing inside SOLIDWORKS",
    description: "Power Surfacing is the industrial design add-in that brings freeform Sub-D surfacing to SOLIDWORKS. Manipulating Power Surfacing parts is as simple as modeling with clay — create complex, aesthetically pleasing Class A surfaces, then convert them directly into SOLIDWORKS features that contain either solid and/or surface bodies.",
    image: IMAGES.solidworks,
    path: "/products/power-surfacing-solidworks",
    testimonialsPath: "/customers/solidworks",
    platform: "SOLIDWORKS Add-in",
    category: "Sub-D Design",
    inputs: ["SOLIDWORKS sketches", "OBJ / FBX meshes"],
    outputs: ["SOLIDWORKS features with solid and/or surface bodies"],
    pricing: {
      options: [
        { label: "Single Seat License", price: "$2,995", detail: "Perpetual license for one user" },
        { label: "Network License", price: "$3,995", detail: "Floating license shared across your team" },
        { label: "Annual Maintenance", price: "$595", period: "/year", detail: "Updates and support" },
      ],
    },
    testimonials: [
      { quote: "I love your program — for me the Power Surfacing plugin represents the most significant advancement in SOLIDWORKS modelling capability in more than a decade!", name: "James Bevan", title: "Duncan Walton London" },
      { quote: "Power Surfacing has exceeded every one of our expectations for delivering fast results in a dynamic editing environment within SOLIDWORKS. We are such fans of the new plugin.", name: "Raquel Rabago", title: "Tovolo" },
      { quote: "The Sub-D approach to complex shape design is COMPLETELY unlike anything you have EVER been able to do in SOLIDWORKS, and yet it complements SOLIDWORKS so well. Their price point is remarkable given the functionality they are bringing to the table.", name: "Jason Pancoast", title: "CAPINC" },
    ],
    features: [
      "Power Body macro-features that behave like native SOLIDWORKS features",
      "Creation directly from SOLIDWORKS sketches",
      "Import of OBJ and FBX meshes from Modo, 3ds Max, and Maya",
      "Dynamic push-pull editing, soft selection, and mirror/bend tools",
      "Editable and creatable directly from SOLIDWORKS assemblies",
      "Conversion into SOLIDWORKS features that contain either solid and/or surface bodies",
      "Full integration with the SOLIDWORKS Feature Tree",
      "Includes Power Shell and Power Thicken at no extra cost",
    ],
    useCases: [
      "Adding organic, freeform surfaces to mechanical assemblies",
      "Consumer product and industrial design inside SOLIDWORKS",
      "Automotive interior, exterior, and sporting goods surfacing",
      "Toy, character, and handheld device design",
      "Editing Power Surface bodies as instances or references across assemblies",
    ],
    whoIsItFor: [
      "SOLIDWORKS users needing freeform surfacing",
      "Industrial designers working inside SOLIDWORKS",
      "Product designers standardized on SOLIDWORKS",
      "Engineering teams designing organic, ergonomic parts",
    ],
    benefits: [
      "Won the TenLinks Best of Show award at SOLIDWORKS World",
      "Backed by an official SOLIDWORKS Gold Partner",
      "Power Body macro-features integrate with the SOLIDWORKS feature tree",
      "Includes Power Shell and Power Thicken at no additional cost",
      "Combines Sub-D freeform design with SOLIDWORKS parametric precision",
    ],
  },
  {
    id: "power-surfacing-re-solidworks",
    name: "Power Surfacing RE for SOLIDWORKS",
    pageTitle: "Power Surfacing RE | SOLIDWORKS Reverse Engineering",
    pageDescription: "Reverse engineer 3D scans, STL meshes, and sculpted models directly inside SOLIDWORKS with automatic retopology and surface fitting.",
    shortName: "Power Surfacing RE",
    tagline: "Reverse engineer scanned and polygonal meshes inside SOLIDWORKS",
    description: "Power Surfacing RE gives SOLIDWORKS users a unique set of tools to rebuild shapes from many meshes — 3D scans, FEA meshes, sculpted meshes, 3D printer files, and online model databases — directly inside SOLIDWORKS, without leaving your native CAD environment. It is primarily targeted at reverse engineering organic data; mechanical data is reconstructed using native SOLIDWORKS tools.",
    image: IMAGES.reSolidworks,
    path: "/products/power-surfacing-re-solidworks",
    testimonialsPath: "/customers/solidworks",
    platform: "SOLIDWORKS Add-in",
    category: "Reverse Engineering",
    inputs: ["3D scans", "STL / OBJ meshes", "Topology Study meshes"],
    outputs: ["SOLIDWORKS solid & surface bodies"],
    pricing: {
      options: [
        { label: "Single Seat License", price: "$3,995", detail: "Perpetual license for one user" },
        { label: "Network License", price: "$4,995", detail: "Floating license shared across your team" },
        { label: "Annual Maintenance", price: "$795", period: "/year", detail: "Updates and support" },
      ],
    },
    testimonials: [
      { quote: "I was able to convert the very complex scan I was working with to a usable surface. It made the workload MUCH easier and I have been able to save at least 40 hours of CAD in this project. Power Surfacing RE has been extremely helpful.", name: "Justin Lefebvre", title: "Derby Building Products Inc." },
      { quote: "Your Power Surfacing RE has been an amazing (and fun) tool to work with. Thanks again for the amazing software — Power Surfacing makes my job fun!", name: "Jesse Maier", title: "Maier Manufacturing, Inc." },
      { quote: "We have some recent successes after the implementation of Power Surfacing which has — in a particular project — phenomenally reduced the time to get parts to tooling, by approximately 4 weeks!", name: "Gavin Colgan-Smith", title: "ARB Corporation Ltd" },
    ],
    features: [
      "Import meshes and display them as a reference mesh",
      "Convert existing SOLIDWORKS geometry into a reference mesh",
      "Quad Wrap retopology with automatic open-edge closing",
      "Shrink Wrap with automatic self-intersection fixes",
      "Mesh Smooth and Mesh Offset tools",
      "Distance display to measure approximation accuracy",
      "SOLIDWORKS Topology Study to solid geometry conversion",
      "Includes the full Power Surfacing toolset",
    ],
    useCases: [
      "Reverse engineering 3D scanner data directly in SOLIDWORKS",
      "Converting ZBrush sculpted meshes into SOLIDWORKS geometry",
      "Rebuilding parts from FEA and 3D printer mesh files",
      "Recreating or modifying existing SOLIDWORKS parts from meshes",
      "Converting SOLIDWORKS Topology Optimization studies into solids",
    ],
    whoIsItFor: [
      "SOLIDWORKS users who need reverse engineering",
      "Engineers working with 3D scanner data",
      "Teams rebuilding legacy parts with no original CAD data",
      "Manufacturing engineers using Topology Optimization studies",
      "Designers needing to convert sculpted (ZBrush, etc.) meshes into a precise CAD NURBS representation",
    ],
    benefits: [
      "Patent-pending technology captures fine scan detail without bloating model size",
      "Follows curvature and flow lines so creases and ridges aren't washed out",
      "Includes the full Power Surfacing toolset at no extra cost",
      "Automated tools to find and fix scan anomalies like tears and holes",
      "Directly converts SOLIDWORKS Topology Study results into solids",
    ],
  },
  {
    id: "power-shell-solidworks",
    name: "Power Shell for SOLIDWORKS",
    pageTitle: "Power Shell for SOLIDWORKS | Advanced Shelling",
    pageDescription: "Shell and thicken complex, organic geometry in cases where the standard SOLIDWORKS Shell and Thicken commands fail. Includes Power Thicken.",
    shortName: "Power Shell",
    tagline: "When Shell fails, Power Shell prevails",
    description: "Power Shell (which includes Power Thicken) solves a long-standing CAD problem — shelling and thickening complex, difficult, or organic surfaces and solids in cases where the standard SOLIDWORKS Shell and Thicken commands fail.",
    image: IMAGES.powerShell,
    path: "/products/power-shell-solidworks",
    testimonialsPath: "/customers/solidworks",
    platform: "SOLIDWORKS Add-in",
    category: "Shelling",
    inputs: ["SOLIDWORKS solids & surfaces"],
    outputs: ["Shelled / thickened SOLIDWORKS bodies"],
    pricing: {
      options: [
        { label: "Single Seat License", price: "$1,495", detail: "Perpetual license for one user" },
      ],
      note: "Included free with Power Surfacing and Power Surfacing RE.",
    },
    testimonials: [
      { quote: "Power Shell really has been amazing. Truly a massive help in frustration and time. SOLIDWORKS shell always fails, and the workarounds are very tedious and time consuming. It's the only 3rd-party tool I've purchased for SOLIDWORKS.", name: "Sean Conner", title: "Hickenbottom, Inc." },
      { quote: "Power Shell. Wow! What a tool. I have been working on a golf club driver head — very organic shapes, sharp features with small break rads. SW on its own would never manage this operation. I'm impressed. Well done and thank you.", name: "Dean Bourne", title: "3D Design Limited" },
      { quote: "Has thrown up many new possibilities and re-design that I could not have done before. Has revolutionised my business in a similar way that Power Surfacing did a few years back. Will save a lot of money and time.", name: "Stuart Brown", title: "3D Engineers" },
    ],
    features: [
      "Shell, Hollow, and Thicken commands",
      "Works with solids (Power Shell) or surfaces (Power Thicken)",
      "Offset inside or outside with clearance values",
      "Handles small radii, large radii, and intersected surfaces",
      "Verification of offset distances (thickness)",
      "Rounding of corners and edges",
      "Undo/Redo with live preview",
      "Full integration with the SOLIDWORKS Feature Tree",
    ],
    useCases: [
      "Shelling organic, complex, or self-intersecting geometry",
      "Thickening surface bodies that fail with native Thicken",
      "Preparing consumer products for injection molding",
      "Creating uniform or variable wall thickness on any geometry",
      "Succeeding on models where SOLIDWORKS Shell produces errors",
    ],
    whoIsItFor: [
      "SOLIDWORKS users with complex shelling needs",
      "Manufacturing engineers preparing parts for injection molding",
      "Product designers working with organic geometry",
      "Engineers working with imported or scanned geometry",
    ],
    benefits: [
      "Solves shelling and thickening failures common to virtually all CAD systems",
      "Patent-pending technology built for complex offsetting cases",
      "Included free with Power Surfacing and Power Surfacing RE",
      "Proven in side-by-side tests where native SOLIDWORKS Shell fails at greater thicknesses",
      "Full feature tree integration with undo/redo and live preview",
    ],
  },
];

export const WORKFLOWS = [
  { id: "reverse-engineering", name: "Reverse Engineering Mechanical Parts", path: "/workflows/reverse-engineering", image: "/assets/wf-reverse-engineering.webp", description: "Convert physical objects and 3D scans into editable CAD geometry using advanced reverse engineering workflows.", startingData: "A physical part or a 3D scan mesh", result: "An editable, manufacturable CAD solid", recommendedProduct: "Power Surfacing RE Studio" },
  { id: "scan-to-cad", name: "Scan-to-CAD", path: "/workflows/scan-to-cad", image: "/assets/wf-scan-to-cad.webp", description: "Transform raw 3D scan data from any scanner into clean, manufacturing-ready CAD surfaces and solids.", startingData: "Raw 3D scanner data (STL, OBJ, point cloud)", result: "Clean NURBS surfaces and solids", recommendedProduct: "Power Surfacing RE Studio" },
  { id: "mesh-to-cad", name: "Mesh-to-CAD", path: "/workflows/mesh-to-cad", image: "/assets/wf-mesh-to-cad.webp", description: "Convert triangulated mesh data into smooth NURBS surfaces and solid CAD models.", startingData: "A triangulated mesh (STL or OBJ)", result: "A smooth NURBS CAD model", recommendedProduct: "Power Surfacing RE Studio" },
  { id: "stl-obj-to-cad", name: "STL to Editable CAD", path: "/workflows/stl-obj-to-cad", image: "/assets/wf-mesh-to-cad.webp", description: "Convert STL and OBJ files into genuinely editable CAD and STEP models — rebuilt surfaces and solids, not wrapped polygons.", startingData: "An STL or OBJ mesh file", result: "Editable CAD solids exportable to STEP", recommendedProduct: "Power Surfacing RE Studio" },
  { id: "sculpted-mesh-to-cad", name: "ZBrush / Sculpted Mesh to CAD", path: "/workflows/sculpted-mesh-to-cad", image: "/assets/wf-zbrush.webp", description: "Convert ZBrush, Mudbox, and other sculpted mesh models into production-ready NURBS CAD surfaces.", startingData: "A ZBrush or other sculpted mesh", result: "Production-ready NURBS CAD surfaces", recommendedProduct: "Power Surfacing RE for SOLIDWORKS" },
  { id: "freeform-sub-d", name: "Freeform Sub-D Design", path: "/workflows/freeform-sub-d", image: "/assets/wf-freeform.webp", description: "Use subdivision surface modeling to create smooth, organic freeform shapes with intuitive control.", startingData: "A freeform or organic design idea", result: "Smooth Class A Sub-D surfaces as NURBS", recommendedProduct: "Power Surfacing Studio" },
  { id: "industrial-design-solidworks", name: "Industrial Design in SOLIDWORKS", path: "/workflows/industrial-design-solidworks", image: "/assets/wf-industrial.webp", description: "Create beautiful, ergonomic industrial designs directly inside SOLIDWORKS using Sub-D surfacing.", startingData: "A SOLIDWORKS part or assembly", result: "Organic Class A surfaces in your feature tree", recommendedProduct: "Power Surfacing for SOLIDWORKS" },
  { id: "shelling-thickening", name: "Shelling and Thickening", path: "/workflows/shelling-thickening", image: "/assets/wf-shelling.webp", description: "Shell and thicken complex geometry that standard CAD tools cannot handle.", startingData: "A complex solid or surface body", result: "A shelled or thickened part with clean walls", recommendedProduct: "Power Shell for SOLIDWORKS (also included in Power Surfacing Studio and Power Surfacing RE Studio)" },
  { id: "cad-visualization", name: "CAD Visualization", path: "/workflows/cad-visualization", image: IMAGES.visualize, description: "Import engineering CAD, clean up assemblies, and create product visuals with bundled KeyShot — or prepare and export meshes for Blender, Modo, 3ds Max, Maya, and other visualization packages.", startingData: "An engineering CAD model (STEP, IGES, SAT, Rhino, SOLIDWORKS, or mesh)", result: "Product visuals with bundled KeyShot, or meshes ready for Blender, Modo, 3ds Max, Maya, OBJ, STL, or glTF", recommendedProduct: "Power Surfacing Visualize (also included in Studio and RE Studio)" },
];

export const CAPABILITIES = [
  { name: "Reverse Engineering", icon: "ScanLine", description: "Convert 3D scans, meshes, and point clouds into editable CAD geometry." },
  { name: "Scan/Mesh-to-CAD", icon: "FileInput", description: "Import and convert STL, OBJ, and mesh files into NURBS surfaces and solid models." },
  { name: "Dimension-Driven Sketching", icon: "Ruler", description: "Precisely control geometry with parametric dimensions, constraints, and relationships." },
  { name: "Feature-Based Modeling", icon: "Layers", description: "Build complex models with a construction history that can be edited and rolled back at any time." },
  { name: "Surfacing & Solids", icon: "Box", description: "Combine surface modeling and solid modeling for complete product design workflows." },
  { name: "Freeform Sub-D Design", icon: "Spline", description: "Create smooth, organic shapes using subdivision surface modeling with intuitive control." },
  { name: "SOLIDWORKS Workflows", icon: "Workflow", description: "Extend SOLIDWORKS with freeform surfacing, reverse engineering, and advanced shelling." },
  { name: "Shelling & Thickening", icon: "Shell", description: "Handle complex shelling and thickening operations that standard tools cannot solve." },
  { name: "CAD Visualization", icon: "Eye", description: "Import engineering CAD, clean up assemblies, and create product visuals with bundled KeyShot rendering." },
];

export const NAV_ITEMS = [
  {
    label: "Products",
    path: "/products",
    children: [
      { label: "All Products", path: "/products" },
      { label: "Power Surfacing Visualize", path: "/products/power-surfacing-visualize" },
      { label: "Power Surfacing RE Studio", path: "/products/power-surfacing-re-studio" },
      { label: "Power Surfacing Studio", path: "/products/power-surfacing-studio" },
      { label: "Power Surfacing for SOLIDWORKS", path: "/products/power-surfacing-solidworks" },
      { label: "Power Surfacing RE for SOLIDWORKS", path: "/products/power-surfacing-re-solidworks" },
      { label: "Power Shell for SOLIDWORKS", path: "/products/power-shell-solidworks" },
      { label: "Compare Products", path: "/products/comparison" },
    ],
  },
  {
    label: "Workflows",
    path: "/workflows",
    children: [
      { label: "All Workflows", path: "/workflows" },
      { label: "Reverse Engineering Mechanical Parts", path: "/workflows/reverse-engineering" },
      { label: "Scan-to-CAD", path: "/workflows/scan-to-cad" },
      { label: "Mesh-to-CAD", path: "/workflows/mesh-to-cad" },
      { label: "STL to Editable CAD", path: "/workflows/stl-obj-to-cad" },
      { label: "ZBrush / Sculpted Mesh to CAD", path: "/workflows/sculpted-mesh-to-cad" },
      { label: "Freeform Sub-D Design", path: "/workflows/freeform-sub-d" },
      { label: "Industrial Design in SOLIDWORKS", path: "/workflows/industrial-design-solidworks" },
      { label: "Shelling and Thickening", path: "/workflows/shelling-thickening" },
      { label: "CAD Visualization", path: "/workflows/cad-visualization" },
    ],
  },
  {
    label: "Learn",
    path: "/resources",
    children: [
      { label: "Learning Center", path: "/resources" },
      { label: "About nPower Software", path: "/about" },
      { label: "Research Publications", path: "/publications" },
      { label: "Patents", path: "/patents" },
      { label: "How It Works", path: "/technology" },
      { label: "Video Library", path: "/resources/videos" },
      { label: "Product Demos", path: "/resources/demos" },
      { label: "Tutorials", path: "/resources/tutorials" },
      { label: "FAQ", path: "/resources/faq" },
      { label: "Newsletter", path: "/newsletter" },
      { label: "Events & Webinars", path: "/events" },
    ],
  },
  {
    label: "Pricing & Licensing",
    path: "/pricing",
    children: [
      { label: "Pricing & Licensing", path: "/pricing" },
      { label: "Pricing", path: "/pricing/plans" },
      { label: "Free Trial", path: "/pricing/trials" },
      { label: "Upgrades & Maintenance", path: "/pricing/upgrades" },
      { label: "Authorized Resellers", path: "/resellers" },
    ],
  },
  {
    label: "Support",
    path: "/support",
    children: [
      { label: "Support Home", path: "/support" },
      { label: "Getting Started", path: "/support/getting-started" },
      { label: "Tutorials by Product", path: "/support/tutorials" },
      { label: "Install & Activate", path: "/support/installation" },
      { label: "System Requirements", path: "/support/system-requirements" },
      { label: "Release Notes", path: "/support/release-notes" },
      { label: "Downloads", path: "/pricing/downloads" },
      { label: "Contact Support", path: "/support/contact" },
    ],
  },
];

function ytThumb(id) {
  return `https://img.youtube.com/vi/${id}/hqdefault.jpg`;
}

export const SAMPLE_VIDEOS = [
  { id: "v1", youtubeId: "yZr-buzOCGc", title: "Solids# MeshToCAD Basic Usage", product: "Power Surfacing RE Studio", type: "Demo", workflow: "Mesh-to-CAD", level: "Beginner", duration: "9:40", thumbnail: ytThumb("yZr-buzOCGc") },
  { id: "v2", youtubeId: "F9U8-l1y3Kw", title: "Solids# MeshToCAD Recorded Webinar", product: "Power Surfacing RE Studio", type: "Overview", workflow: "Reverse Engineering Mechanical Parts", level: "Beginner", duration: "34:20", thumbnail: ytThumb("F9U8-l1y3Kw") },
  { id: "v3", youtubeId: "tVl9xQwSiCE", title: "Power Surfacing Technology Overview", product: "Power Surfacing Studio", type: "Overview", workflow: "Freeform Sub-D Design", level: "Beginner", duration: "5:22", thumbnail: ytThumb("tVl9xQwSiCE") },
  { id: "v4", youtubeId: "WI17SjGiXaE", title: "Gas Can Modeling Tutorial", product: "Power Surfacing Studio", type: "Tutorial", workflow: "Feature-Based Modeling", level: "Beginner", duration: "18:05", thumbnail: ytThumb("WI17SjGiXaE") },
  { id: "v5", youtubeId: "ombvLO6vu9c", title: "Signet Ring Build", product: "Power Surfacing Studio", type: "Tutorial", workflow: "Freeform Sub-D Design", level: "Intermediate", duration: "12:50", thumbnail: ytThumb("ombvLO6vu9c") },
  { id: "v6", youtubeId: "k-Bxe4Al_VQ", title: "Getting Started with Power Surfacing", product: "Power Surfacing for SOLIDWORKS", type: "Tutorial", workflow: "Industrial Design in SOLIDWORKS", level: "Beginner", duration: "14:15", thumbnail: ytThumb("k-Bxe4Al_VQ") },
  { id: "v7", youtubeId: "Fjg35m5MTMI", title: "Understanding the Gizmo", product: "Power Surfacing for SOLIDWORKS", type: "Tutorial", workflow: "Freeform Sub-D Design", level: "Beginner", duration: "7:30", thumbnail: ytThumb("Fjg35m5MTMI") },
  { id: "v8", youtubeId: "rP7KfmP0Mkg", title: "Creating a Custom Ring in SOLIDWORKS", product: "Power Surfacing for SOLIDWORKS", type: "Tutorial", workflow: "Industrial Design in SOLIDWORKS", level: "Intermediate", duration: "16:45", thumbnail: ytThumb("rP7KfmP0Mkg") },
  { id: "v9", youtubeId: "pvLbDM9f58A", title: "Embossed Brick Pattern Tutorial", product: "Power Surfacing for SOLIDWORKS", type: "Tutorial", workflow: "Freeform Sub-D Design", level: "Intermediate", duration: "9:10", thumbnail: ytThumb("pvLbDM9f58A") },
  { id: "v10", youtubeId: "l87K8yfbEdY", title: "Power Surfacing 10.0 New Features", product: "Power Surfacing for SOLIDWORKS", type: "Overview", workflow: "Feature-Based Modeling", level: "Intermediate", duration: "11:20", thumbnail: ytThumb("l87K8yfbEdY") },
  { id: "v11", youtubeId: "sceEZzxyvTg", title: "Power Surfacing RE 5.0 Overview", product: "Power Surfacing RE for SOLIDWORKS", type: "Overview", workflow: "Reverse Engineering", level: "Beginner", duration: "13:40", thumbnail: "https://img.youtube.com/vi/sceEZzxyvTg/default.jpg" },
  { id: "v12", youtubeId: "4LjOmm-u8XI", title: "Reverse Engineering Scanned Meshes in SOLIDWORKS", product: "Power Surfacing RE for SOLIDWORKS", type: "Demo", workflow: "Scan-to-CAD", level: "Intermediate", duration: "28:15", thumbnail: ytThumb("4LjOmm-u8XI") },
  { id: "v13", youtubeId: "SIX_m3N37e4", title: "Converting ZBrush Meshes to SOLIDWORKS (ZBrush Remesher)", product: "Power Surfacing RE for SOLIDWORKS", type: "Tutorial", workflow: "ZBrush / Sculpted Mesh to CAD", level: "Intermediate", duration: "10:35", thumbnail: ytThumb("SIX_m3N37e4") },
  { id: "v14", youtubeId: "dtXuwIIwNcY", title: "Working with Topology Study Meshes", product: "Power Surfacing RE for SOLIDWORKS", type: "Demo", workflow: "Topology Optimization to CAD", level: "Advanced", duration: "12:05", thumbnail: ytThumb("dtXuwIIwNcY") },
  { id: "v15", youtubeId: "Cd439HkG9ow", title: "Quad Wrap Options Explained", product: "Power Surfacing RE for SOLIDWORKS", type: "Tutorial", workflow: "Mesh-to-CAD", level: "Intermediate", duration: "8:50", thumbnail: ytThumb("Cd439HkG9ow") },
  { id: "v16", youtubeId: "bUTIEH12be4", title: "Reverse Engineering Real World Scans", product: "Power Surfacing RE for SOLIDWORKS", type: "Demo", workflow: "Scan-to-CAD", level: "Advanced", duration: "15:30", thumbnail: ytThumb("bUTIEH12be4") },
  { id: "v17", youtubeId: "2s9nVQPv0Ak", title: "Power Shell Introduction", product: "Power Shell for SOLIDWORKS", type: "Overview", workflow: "Shelling and Thickening", level: "Beginner", duration: "6:15", thumbnail: ytThumb("2s9nVQPv0Ak") },
  { id: "v18", youtubeId: "IeAlGJJtXps", title: "Power Shell Presentation", product: "Power Shell for SOLIDWORKS", type: "Demo", workflow: "Shelling and Thickening", level: "Beginner", duration: "9:00", thumbnail: ytThumb("IeAlGJJtXps") },
];
