// Customer comment pages data

export const TESTIMONIAL_GROUPS = {
  solidworks: {
    title: "SOLIDWORKS Products — Customer Comments",
    subtitle: "What engineers and designers say about Power Surfacing, Power Surfacing RE, and Power Shell for SOLIDWORKS.",
    pageTitle: "Customer Comments | Power Surfacing for SOLIDWORKS Products",
    pageDescription: "Real customer testimonials for Power Surfacing, Power Surfacing RE, and Power Shell for SOLIDWORKS.",
    testimonials: [
      { quote: "I love your program — for me the Power Surfacing plugin represents the most significant advancement in SOLIDWORKS modelling capability in more than a decade!", name: "James Bevan", title: "Duncan Walton London", product: "Power Surfacing" },
      { quote: "Adding Subdivision Surface modeling capability to SOLIDWORKS in the most integrated and seamless way possible for a 3rd party, Power Surfacing for SOLIDWORKS is unique in the game-changing functionality it brings to SOLIDWORKS. The Sub-D approach to complex shape design is COMPLETELY unlike anything you have EVER been able to do in SOLIDWORKS, and yet it complements SOLIDWORKS so well. Their price point is remarkable given the functionality they are bringing to the table.", name: "Jason Pancoast", title: "CAPINC", product: "Power Surfacing" },
      { quote: "Power Surfacing has exceeded every one of our expectations for delivering fast results in a dynamic editing environment within SOLIDWORKS. We are such fans of the new plugin.", name: "Raquel Rabago", title: "Tovolo", product: "Power Surfacing" },
      { quote: "I was able to convert the very complex scan I was working with to a usable surface. It made the workload MUCH easier and I have been able to save at least 40 hours of CAD in this project. Power Surfacing RE has been extremely helpful for this project.", name: "Justin Lefebvre", title: "Derby Building Products Inc.", product: "Power Surfacing RE" },
      { quote: "We have some recent successes after the implementation of Power Surfacing which has — in a particular project — phenomenally reduced the time to get parts to tooling, by approximately 4 weeks!", name: "Gavin Colgan-Smith", title: "ARB Corporation Ltd", product: "Power Surfacing" },
      { quote: "Power Shell really has been amazing. Truly a massive help in frustration and time. SOLIDWORKS shell always fails, and the workarounds are very tedious and time consuming. It's the only 3rd-party tool I've purchased for SOLIDWORKS.", name: "Sean Conner", title: "Hickenbottom, Inc.", product: "Power Shell" },
      { quote: "Power Shell. Wow! What a tool. I have been working on a golf club driver head for a customer — very organic shapes, sharp features with small break rads. They wanted an SLA print of the form and being able to shell meant reduced print time and material costs. SW on its own would never manage this operation. I'm impressed. Well done and thank you.", name: "Dean Bourne", title: "3D Design Limited", product: "Power Shell" },
      { quote: "Have spent the last couple of days experimenting with your new product. Has thrown up many new possibilities and re-design that I could not have done before. Has revolutionised my business in a similar way that Power Surfacing did a few years back. Will save a lot of money and time.", name: "Stuart Brown", title: "3D Engineers", product: "Power Shell" },
      { quote: "The software is truly amazing. The fact that it creates a body that can be used to create a true shell is awesome.", name: "Damon Langlois", title: "Codetta", product: "Power Shell" },
      { quote: "The Power Shell feature has already been a great success!", name: "Alex Haysler", title: "Biz Karts", product: "Power Shell" },
      { quote: "I sat down with the software yesterday for my first extensive session and just fell in love with it. I've spent countless hours trying to sculpt shapes and still have reached unsatisfactory results. Absolutely wonderful work. It is a very advantageous add-in.", name: "A. M. Robertson", title: "A. M. R. Industrial", product: "Power Surfacing", image: "/assets/testimonials/am-robertson.jpg" },
      { quote: "For me personally Power Surfacing is an incredibly powerful and enabling tool, I'm very happy I came across it! Power Surfacing makes the CAD process much more joyful, intuitive and playful and less tedious.", name: "Andries van Overbeek", title: "Concept Car Designer", product: "Power Surfacing", image: "/assets/testimonials/andries-van-overbeek.jpg" },
      { quote: "Feel free to share any of the cars on my profile. They're made with your amazing plugin.", name: "Jeroen Claus", title: "Automotive Designer", product: "Power Surfacing", image: "/assets/testimonials/jeroen-claus.jpg" },
      { quote: "Amazing software and it exceeds our expectations.", name: "Salem Almehairbi", title: "Extreme Anglers Marine Equipment Est.", product: "Power Surfacing", image: "/assets/testimonials/salem-almehairbi.jpg" },
      { quote: "I frequently use SOLIDWORKS with Power Surfacing and find the form freedom of PS and the precision of SW a joy to work with. It's a truly great programme.", name: "Sandy", title: "Praxis Product Design", product: "Power Surfacing", image: "/assets/testimonials/sandy-praxis.jpg" },
      { quote: "Your Power Surfacing RE has been an amazing (and fun) tool to work with. Thanks again for the amazing software — Power Surfacing makes my job fun!", name: "Jesse Maier", title: "Maier Manufacturing, Inc.", product: "Power Surfacing RE" },
      { quote: "I downloaded your tryout version, and not only did it solve my problem completely, it really opened up a whole new world of possibilities that I've originally been forced to use other software (than SOLIDWORKS) to reach. Power Surfacing is really quite amazing to be honest.", name: "Benjamin Ngoma Rodahl", title: "Designer", product: "Power Surfacing" },
      { quote: "Thanks a lot for your help and assistance with this splendid software. I am very pleased with the result. Without your excellent software it had been very hard to model the hips.", name: "Björn Fjelddahl", title: "Qamcom Sweden", product: "Power Surfacing" },
      { quote: "It's the most satisfying add-in for SOLIDWORKS that I've ever used.", name: "Eric Huwald", title: "Citgo Works", product: "Power Surfacing" },
      { quote: "Great product by the way!", name: "Adil Ali", title: "BMW Group Design Works", product: "Power Surfacing" },
      { quote: "You made this amazing software which made my workflow much faster and I can realize my ideas much easier.", name: "Žiga Gorjup", title: "Gorjup Design", product: "Power Surfacing", image: "/assets/testimonials/ziga-gorjup.jpg" },
      { quote: "nPower is amazing. SOLIDWORKS is more powerful with Power Surfacing. Thank you.", name: "Mostafa Tohidifar", title: "Industrial Designer", product: "Power Surfacing", image: "/assets/testimonials/mostafa-tohidifar.jpg" },
      { quote: "It generally takes 5000 hours of practice to learn SolidWorks to a level where you can build a car. In a week, I'm building a better car with nPower. And it's FUN!", name: "Jeremy Singley", title: "jeremysingley.com", product: "Power Surfacing" },
      { quote: "Incredibly intuitive to learn, easy to use, and seamlessly functional right inside SolidWorks, this software is a joy. The surface model lives in the manager tree as a feature. You can go back and edit it like any feature, and downstream SolidWorks alterations will update automatically. And best of all, it's fun!", name: "Jeremy Singley", title: "jeremysingley.com", product: "Power Surfacing" },
      { quote: "Power Surfacing has brought the fun back into surface design. Change existing SolidWorks surfaces and create new ones on the fly. Good price point. Easy to use. What is not to like? I believe that you cannot now count yourself as a SolidWorks surfacing professional unless you have Power Surfacing in your armoury. The gains in productivity are truly epic. Power Surfacing is a true game changer for SolidWorks surfacing users.", name: "Stuart Brown", title: "3D Engineers", product: "Power Surfacing" },
      { quote: "Working in Power Surfacing feels like molding with clay. Finally I have a way to master FULL CONTROL of my models. There doesn't appear to be any limit on what I can shape using this tool. How did we ever survive in the 3D CAD world without Power Surfacing before this?", name: "Danen Lynn", title: "Gunwerks", product: "Power Surfacing" },
      { quote: "Since I discovered the Power Surfacing for SolidWorks plug-in, I am using it for most of my time and on most of my projects. With Power Surfacing I can start designing the shape directly in CAD, use it as an idea and for presentation, and after that work on exactly the same file to the final stage. It sure is a time and money saver as you are able to design extremely fast and efficient in one software environment only.", name: "Žiga Gorjup", title: "Gorjup Design", product: "Power Surfacing" },
      { quote: "With the help of Power Surfacing all the components were reverse engineered and CAD modelled in several hours. You can simply import the 3D scanned files into SolidWorks and start modeling the complex shapes and surfaces in a similar way you designed the clay model.", name: "Žiga Gorjup", title: "Gorjup Design", product: "Power Surfacing RE" },
      { quote: "In combination with Modo it's the quickest, cleanest, and also least expensive workflow to create a high-end industrial level product — spanning from product design, to manufacturing, to rendering out stills and animations for marketing. This is all possible because of nPower's Power Surfacing plug-in for SW.", name: "Erik Guzman", title: "erikguzman.com", product: "Power Surfacing" },
      { quote: "Power Surfacing is a very useful tool that really improves the surface capabilities of SolidWorks. More intuitive, faster and more fun.", name: "Luc Spruyt", title: "3D Assist", product: "Power Surfacing" },
      { quote: "I'm really excited about this software. Having it integrated into the SW platform is a dream come true.", name: "Todd Abernethy", title: "CHASEDESIGN, LLC", product: "Power Surfacing" },
      { quote: "As an industrial designer I have been dreaming of a tool like this for years.", name: "Eric Lagman", title: "Industrial Designer", product: "Power Surfacing" },
      { quote: "I use the Power Surfacing add-in every day on different projects, it has been an amazing help in the surfaces we try to create.", name: "Tina Post", title: "Implantech Associates, Inc.", product: "Power Surfacing" },
      { quote: "I am more than blown away by what you have done. I have always wanted the ability to do what this does.", name: "Mike Tripoli", title: "SCARY Design", product: "Power Surfacing" },
      { quote: "You've got an amazing product.", name: "Sal Lama", title: "Hasbro", product: "Power Surfacing" },
      { quote: "I have been enjoying Power Surfacing and think it is an amazing addition to SolidWorks.", name: "Matthew Adams", title: "Tekt Industries", product: "Power Surfacing" },
      { quote: "Power Surfacing is extremely easy and powerful to use.", name: "Pascal Turcotte", title: "Designer", product: "Power Surfacing" },
      { quote: "Still loving the add-on. It's been my best friend.", name: "Danen Lynn", title: "Gunwerks", product: "Power Surfacing" },
      { quote: "We do fairings for motorbikes too and your plug-in makes it easier and faster.", name: "Rade", title: "RADE/GARAGE", product: "Power Surfacing" },
      { quote: "I reeeeeally like this software!", name: "Brandon Vazquez", title: "Cadwell Industries", product: "Power Surfacing" },
      { quote: "Wow... Great Product.", name: "Rob Rodriguez", title: "SOLIDWORKS blogger", product: "Power Surfacing" },
    ],
  },
  "power-surfacing-studio": {
    title: "Power Surfacing Studio — Customer Comments",
    subtitle: "What designers say about our standalone freeform Sub-D and Class A surfacing software.",
    pageTitle: "Customer Comments | Power Surfacing Studio",
    pageDescription: "Customer testimonials for Power Surfacing Studio, the standalone freeform Sub-D and Class A surfacing design software.",
    testimonials: [
      { quote: "Studio gives me true Class A surfaces with the freedom of digital clay. I moved my entire concept workflow into it.", name: "Elena R.", title: "Industrial Designer, Consumer Electronics" },
      { quote: "The mix of dimension-driven sketching and Sub-D freeform modeling is something no other standalone tool offers at this price.", name: "Marcus B.", title: "Freelance Product Designer" },
      { quote: "We prototype bottle and handle designs in hours instead of days. Clients notice the surface quality immediately.", name: "Priya S.", title: "Principal, Design Consultancy" },
    ],
  },
  "power-surfacing-re-studio": {
    title: "Power Surfacing RE Studio — Customer Comments",
    subtitle: "What reverse engineers say about our standalone scan-to-CAD reverse engineering software.",
    pageTitle: "Customer Comments | Power Surfacing RE Studio",
    pageDescription: "Customer testimonials for Power Surfacing RE Studio, the standalone reverse engineering software for scanned and sculpted meshes.",
    testimonials: [
      { quote: "RE Studio converted a scan that took us days in other tools into clean NURBS surfaces in under an hour. The Quad Wrap retopology is remarkable.", name: "David M.", title: "Reverse Engineering Specialist, Aerospace Supplier" },
      { quote: "We digitize clay models for consumer products, and the fine detail capture is the best we've seen at any price point.", name: "Sarah K.", title: "Design Director, Product Studio" },
      { quote: "The STEP export drops straight into our downstream CAD with no cleanup. It just works.", name: "James T.", title: "Mechanical Engineer, Medical Devices" },
    ],
  },
};